import { TRPCError } from "@trpc/server";
import { desc, eq, inArray } from "drizzle-orm";
import { randomUUID } from "crypto";
import { z } from "zod";
import {
  agents, auditLogs, customers, productPriceTiers, products, remunerationProfiles, saleCommissions, sellerCredentials,
  saleItems, salePayments, sales, saleSettings, stockAlerts, stockMovements, users,
} from "../../drizzle/schema";
import { commissionCents, priceForCustomer, priceForQuantityTier } from "../commerceRules";
import { getDb } from "../db";
import { adminProcedure, protectedProcedure, router } from "../_core/trpc";
import { resultingStock, signedMovementQuantity } from "../stockRules";
import { hashPassword } from "../passwords";
import { storagePut } from "../storage";
import { customerCanBeRemoved } from "../customerRules";

const optionalAlphaReference = z.string().trim().max(80).regex(/^[A-Za-z0-9]*$/, "La référence doit être alphanumérique.").nullable();
const customerInput = z.object({ name: z.string().trim().min(2).max(180), otherReference: optionalAlphaReference, type: z.enum(["ordinary", "wholesale"]), contactName: z.string().trim().max(160).nullable(), email: z.string().trim().email().max(320).nullable(), phone: z.string().trim().max(50).nullable(), address: z.string().trim().max(1000).nullable() });
const agentInput = z.object({ name: z.string().trim().min(2).max(160), type: z.enum(["sales_agent", "cashier"]), email: z.string().trim().email().max(320).nullable(), phone: z.string().trim().max(50).nullable(), active: z.boolean() });
const remunerationInput = z.object({ remunerationMode: z.enum(["fixed", "commission", "fixed_plus_commission"]), fixedMonthlyCents: z.number().int().min(0), commissionBasis: z.enum(["revenue", "net_profit"]), rateBasisPoints: z.number().int().min(0).max(10000), active: z.boolean() });
const sellerInput = z.object({ name: z.string().trim().min(2).max(160), email: z.string().trim().email().max(320).nullable(), username: z.string().trim().min(3).max(80).regex(/^[a-zA-Z0-9._-]+$/), password: z.string().min(8).max(128), remuneration: remunerationInput });
const companyIdentityInput = z.object({ companyName: z.string().trim().min(2).max(200).optional(), companyLogoUrl: z.string().max(1024).nullable().optional(), companySignatureUrl: z.string().max(1024).nullable().optional(), companySignatureLabel: z.string().trim().min(2).max(120).optional(), companyAgreementLabel: z.string().trim().min(2).max(120).optional(), companySignatureAlignment: z.enum(["left", "center", "right"]).optional(), companyAddress: z.string().trim().max(1500).nullable().optional(), companyPhone: z.string().trim().max(50).nullable().optional(), companyEmail: z.string().trim().email().max(320).nullable().optional(), companyFooter: z.string().trim().max(1000).nullable().optional(), ticketHeader: z.string().trim().min(2).max(160).optional(), ticketFooter: z.string().trim().min(2).max(240).optional(), ticketWidthMm: z.enum(["58", "80"]).optional() });

async function dbOrThrow() {
  const db = await getDb();
  if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Base de données indisponible." });
  return db;
}

async function audit(actorUserId: number, action: string, entityType: string, entityId: string | number | null, detail: string) {
  const db = await dbOrThrow();
  await db.insert(auditLogs).values({ actorUserId, action, entityType, entityId: entityId === null ? null : String(entityId), detail });
}

async function listSales(limit = 100) {
  const db = await dbOrThrow();
  return db.select({ id: sales.id, invoiceNumber: sales.invoiceNumber, status: sales.status, paymentMethod: sales.paymentMethod, totalCents: sales.totalCents, netProfitCents: sales.netProfitCents, createdAt: sales.createdAt, customerName: customers.name, customerType: customers.type, sellerName: users.name, salesAgentName: agents.name })
    .from(sales).innerJoin(customers, eq(sales.customerId, customers.id)).leftJoin(users, eq(sales.sellerUserId, users.id)).leftJoin(agents, eq(sales.salesAgentId, agents.id)).orderBy(desc(sales.createdAt)).limit(limit);
}

export const commerceRouter = router({
  customers: router({
    list: protectedProcedure.query(async () => (await dbOrThrow()).select().from(customers).orderBy(customers.name)),
    create: adminProcedure.input(customerInput).mutation(async ({ ctx, input }) => { const db = await dbOrThrow(); const result = await db.insert(customers).values(input); const id = Number(result[0].insertId); await audit(ctx.user.id, "Création", "Client", id, `Client ${input.name} créé`); return { id }; }),
    update: adminProcedure.input(customerInput.extend({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await dbOrThrow(); const { id, ...data } = input; await db.update(customers).set(data).where(eq(customers.id, id)); await audit(ctx.user.id, "Modification", "Client", id, `Client ${data.name} modifié`); return { success: true }; }),
    remove: adminProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await dbOrThrow(); const current = (await db.select().from(customers).where(eq(customers.id, input.id)).limit(1))[0]; if (!current) throw new TRPCError({ code: "NOT_FOUND", message: "Client introuvable." }); const invoices = await db.select({ id: sales.id }).from(sales).where(eq(sales.customerId, input.id)).limit(1); if (!customerCanBeRemoved(invoices.length)) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Ce client est lié à des factures et ne peut pas être supprimé." }); await db.delete(customers).where(eq(customers.id, input.id)); await audit(ctx.user.id, "Suppression", "Client", input.id, `Client ${current.name} supprimé`); return { success: true }; }),
  }),
  agents: router({
    list: protectedProcedure.query(async () => (await dbOrThrow()).select().from(agents).orderBy(agents.name)),
    create: adminProcedure.input(agentInput.extend({ remuneration: remunerationInput })).mutation(async ({ ctx, input }) => { const db = await dbOrThrow(); const { remuneration, ...agentData } = input; const result = await db.insert(agents).values(agentData); const id = Number(result[0].insertId); await db.insert(remunerationProfiles).values({ beneficiaryType: "agent", beneficiaryId: id, ...remuneration }); await audit(ctx.user.id, "Création", "Agent", id, `Agent ${input.name} créé avec rémunération`); return { id }; }),
    update: adminProcedure.input(agentInput.extend({ id: z.number().int().positive(), remuneration: remunerationInput })).mutation(async ({ ctx, input }) => { const db = await dbOrThrow(); const { id, remuneration, ...data } = input; await db.update(agents).set(data).where(eq(agents.id, id)); const profile = (await db.select().from(remunerationProfiles)).find(item => item.beneficiaryType === "agent" && item.beneficiaryId === id); if (profile) await db.update(remunerationProfiles).set(remuneration).where(eq(remunerationProfiles.id, profile.id)); else await db.insert(remunerationProfiles).values({ beneficiaryType: "agent", beneficiaryId: id, ...remuneration }); await audit(ctx.user.id, "Modification", "Agent", id, `Agent ${data.name} modifié`); return { success: true }; }),
    remove: adminProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await dbOrThrow(); await db.update(agents).set({ active: false }).where(eq(agents.id, input.id)); await audit(ctx.user.id, "Suppression", "Agent", input.id, "Agent désactivé et conservé dans l’historique"); return { success: true }; }),
    convertToSeller: adminProcedure.input(z.object({ id: z.number().int().positive(), username: z.string().trim().min(3).max(80).regex(/^[a-zA-Z0-9._-]+$/), password: z.string().min(8).max(128), remuneration: remunerationInput })).mutation(async ({ ctx, input }) => { const db = await dbOrThrow(); const source = (await db.select().from(agents).where(eq(agents.id, input.id)).limit(1))[0]; if (!source || !source.active) throw new TRPCError({ code: "NOT_FOUND", message: "Agent actif introuvable." }); try { const result = await db.insert(users).values({ openId: `local_seller_${randomUUID()}`, name: source.name, email: source.email, loginMethod: "password", role: "seller", active: true }); const userId = Number(result[0].insertId); await db.insert(sellerCredentials).values({ userId, username: input.username, passwordHash: await hashPassword(input.password) }); await db.insert(remunerationProfiles).values({ beneficiaryType: "user", beneficiaryId: userId, ...input.remuneration }); await db.update(agents).set({ active: false }).where(eq(agents.id, source.id)); await audit(ctx.user.id, "Conversion", "Agent", source.id, `${source.name} converti en vendeur (${input.username})`); return { id: userId }; } catch (error) { throw new TRPCError({ code: "CONFLICT", message: "Ce nom d’utilisateur est déjà utilisé.", cause: error }); } }),
    convertSellerToAgent: adminProcedure.input(z.object({ id: z.number().int().positive(), type: z.enum(["sales_agent", "cashier"]), phone: z.string().trim().max(50).nullable(), remuneration: remunerationInput })).mutation(async ({ ctx, input }) => { if (ctx.user.id === input.id) throw new TRPCError({ code: "BAD_REQUEST", message: "Vous ne pouvez pas convertir votre propre compte vendeur." }); const db = await dbOrThrow(); const source = (await db.select().from(users).where(eq(users.id, input.id)).limit(1))[0]; if (!source || source.role !== "seller" || !source.active) throw new TRPCError({ code: "NOT_FOUND", message: "Vendeur actif introuvable." }); const result = await db.insert(agents).values({ name: source.name || "Agent", type: input.type, email: source.email, phone: input.phone, active: true }); const agentId = Number(result[0].insertId); await db.insert(remunerationProfiles).values({ beneficiaryType: "agent", beneficiaryId: agentId, ...input.remuneration }); await db.update(users).set({ active: false }).where(eq(users.id, source.id)); await audit(ctx.user.id, "Conversion", "Vendeur", source.id, `${source.name || "Vendeur"} converti en ${input.type === "cashier" ? "caissier" : "agent commercial"}`); return { id: agentId }; }),
  }),
  sellers: router({
    list: adminProcedure.query(async () => { const db = await dbOrThrow(); return db.select({ id: users.id, name: users.name, email: users.email, active: users.active, username: sellerCredentials.username }).from(users).innerJoin(sellerCredentials, eq(sellerCredentials.userId, users.id)).where(eq(users.role, "seller")).orderBy(users.name); }),
    create: adminProcedure.input(sellerInput).mutation(async ({ ctx, input }) => { const db = await dbOrThrow(); const openId = `local_seller_${randomUUID()}`; try { const result = await db.insert(users).values({ openId, name: input.name, email: input.email, loginMethod: "password", role: "seller", active: true }); const userId = Number(result[0].insertId); await db.insert(sellerCredentials).values({ userId, username: input.username, passwordHash: await hashPassword(input.password) }); await db.insert(remunerationProfiles).values({ beneficiaryType: "user", beneficiaryId: userId, ...input.remuneration }); await audit(ctx.user.id, "Création", "Vendeur", userId, `Vendeur ${input.name} créé avec identifiant ${input.username}`); return { id: userId }; } catch (error) { throw new TRPCError({ code: "CONFLICT", message: "Ce nom d’utilisateur est déjà utilisé.", cause: error }); } }),
    update: adminProcedure.input(sellerInput.extend({ id: z.number().int().positive(), password: z.string().min(8).max(128).optional() })).mutation(async ({ ctx, input }) => { const db = await dbOrThrow(); const { id, username, password, remuneration, ...userData } = input; await db.update(users).set({ name: userData.name, email: userData.email }).where(eq(users.id, id)); const credential = (await db.select().from(sellerCredentials).where(eq(sellerCredentials.userId, id)).limit(1))[0]; if (!credential) throw new TRPCError({ code: "NOT_FOUND", message: "Identifiants vendeur introuvables." }); const credentialData: { username: string; passwordHash?: string } = { username }; if (password) credentialData.passwordHash = await hashPassword(password); await db.update(sellerCredentials).set(credentialData).where(eq(sellerCredentials.id, credential.id)); const profile = (await db.select().from(remunerationProfiles)).find(item => item.beneficiaryType === "user" && item.beneficiaryId === id); if (profile) await db.update(remunerationProfiles).set(remuneration).where(eq(remunerationProfiles.id, profile.id)); else await db.insert(remunerationProfiles).values({ beneficiaryType: "user", beneficiaryId: id, ...remuneration }); await audit(ctx.user.id, "Modification", "Vendeur", id, `Vendeur ${input.name} modifié`); return { success: true }; }),
    remove: adminProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { if (ctx.user.id === input.id) throw new TRPCError({ code: "BAD_REQUEST", message: "Vous ne pouvez pas désactiver votre propre compte." }); const db = await dbOrThrow(); await db.update(users).set({ active: false }).where(eq(users.id, input.id)); await audit(ctx.user.id, "Suppression", "Vendeur", input.id, "Vendeur désactivé et conservé dans l’historique"); return { success: true }; }),
  }),
  settings: router({
    get: protectedProcedure.query(async () => { const db = await dbOrThrow(); return (await db.select().from(saleSettings).limit(1))[0] ?? null; }),
    save: adminProcedure.input(z.object({ defaultSalesAgentId: z.number().int().positive().nullable(), defaultCashierId: z.number().int().positive().nullable(), requireSalesAgent: z.boolean(), requireCashier: z.boolean(), currency: z.enum(["USD", "EUR", "XOF"]).default("XOF"), primaryColor: z.string().regex(/^#[0-9a-fA-F]{6}$/, "La couleur principale doit être au format hexadécimal.").optional(), paymentCashEnabled: z.boolean().optional(), paymentCardEnabled: z.boolean().optional(), paymentMobileMoneyEnabled: z.boolean().optional(), paymentBankTransferEnabled: z.boolean().optional(), paymentCreditEnabled: z.boolean().optional() }).merge(companyIdentityInput)).mutation(async ({ ctx, input }) => { const db = await dbOrThrow(); const current = (await db.select().from(saleSettings).limit(1))[0]; const data = { ...input, primaryColor: input.primaryColor?.toUpperCase() ?? current?.primaryColor ?? "#007B8B", companyName: input.companyName ?? current?.companyName ?? "StockPilot", companyLogoUrl: input.companyLogoUrl ?? current?.companyLogoUrl ?? null, companySignatureUrl: input.companySignatureUrl ?? current?.companySignatureUrl ?? null, companySignatureLabel: input.companySignatureLabel ?? current?.companySignatureLabel ?? "Signature & cachet", companyAgreementLabel: input.companyAgreementLabel ?? current?.companyAgreementLabel ?? "Bon pour accord", companySignatureAlignment: input.companySignatureAlignment ?? current?.companySignatureAlignment ?? "right", companyAddress: input.companyAddress ?? current?.companyAddress ?? null, companyPhone: input.companyPhone ?? current?.companyPhone ?? null, companyEmail: input.companyEmail ?? current?.companyEmail ?? null, companyFooter: input.companyFooter ?? current?.companyFooter ?? null, ticketHeader: input.ticketHeader ?? current?.ticketHeader ?? "Merci de votre achat", ticketFooter: input.ticketFooter ?? current?.ticketFooter ?? "À bientôt", ticketWidthMm: input.ticketWidthMm ?? current?.ticketWidthMm ?? "80", paymentCashEnabled: input.paymentCashEnabled ?? current?.paymentCashEnabled ?? true, paymentCardEnabled: input.paymentCardEnabled ?? current?.paymentCardEnabled ?? true, paymentMobileMoneyEnabled: input.paymentMobileMoneyEnabled ?? current?.paymentMobileMoneyEnabled ?? true, paymentBankTransferEnabled: input.paymentBankTransferEnabled ?? current?.paymentBankTransferEnabled ?? true, paymentCreditEnabled: input.paymentCreditEnabled ?? current?.paymentCreditEnabled ?? true, updatedByUserId: ctx.user.id }; if (current) await db.update(saleSettings).set(data).where(eq(saleSettings.id, current.id)); else await db.insert(saleSettings).values(data); await audit(ctx.user.id, "Paramètres mis à jour", "Entreprise", null, `Paramètres et identité ${data.companyName} mis à jour`); return { success: true }; }),
    uploadLogo: adminProcedure.input(z.object({ dataUrl: z.string().min(30).max(4_000_000), filename: z.string().trim().min(1).max(120) })).mutation(async ({ ctx, input }) => { const match = input.dataUrl.match(/^data:(image\/(?:png|jpeg|webp|svg\+xml));base64,([A-Za-z0-9+/=]+)$/); if (!match) throw new TRPCError({ code: "BAD_REQUEST", message: "Le logo doit être une image PNG, JPEG, WEBP ou SVG." }); const mimeType = match[1]; const buffer = Buffer.from(match[2], "base64"); if (buffer.byteLength > 2 * 1024 * 1024) throw new TRPCError({ code: "PAYLOAD_TOO_LARGE", message: "Le logo ne doit pas dépasser 2 Mo." }); const extension = mimeType === "image/jpeg" ? "jpg" : mimeType === "image/svg+xml" ? "svg" : mimeType.split("/")[1]; const { url } = await storagePut(`company/${ctx.user.id}/logo.${extension}`, buffer, mimeType); const db = await dbOrThrow(); const current = (await db.select().from(saleSettings).limit(1))[0]; if (current) await db.update(saleSettings).set({ companyLogoUrl: url, updatedByUserId: ctx.user.id }).where(eq(saleSettings.id, current.id)); else await db.insert(saleSettings).values({ companyLogoUrl: url, updatedByUserId: ctx.user.id }); await audit(ctx.user.id, "Logo mis à jour", "Entreprise", null, `Logo ${input.filename} enregistré`); return { url }; }),
    uploadSignature: adminProcedure.input(z.object({ dataUrl: z.string().min(30).max(4_000_000), filename: z.string().trim().min(1).max(120) })).mutation(async ({ ctx, input }) => { const match = input.dataUrl.match(/^data:(image\/(?:png|jpeg|webp|svg\+xml));base64,([A-Za-z0-9+/=]+)$/); if (!match) throw new TRPCError({ code: "BAD_REQUEST", message: "La signature doit être une image PNG, JPEG, WEBP ou SVG." }); const mimeType = match[1]; const buffer = Buffer.from(match[2], "base64"); if (buffer.byteLength > 2 * 1024 * 1024) throw new TRPCError({ code: "PAYLOAD_TOO_LARGE", message: "La signature ne doit pas dépasser 2 Mo." }); const extension = mimeType === "image/jpeg" ? "jpg" : mimeType === "image/svg+xml" ? "svg" : mimeType.split("/")[1]; const { url } = await storagePut(`company/${ctx.user.id}/signature.${extension}`, buffer, mimeType); const db = await dbOrThrow(); const current = (await db.select().from(saleSettings).limit(1))[0]; if (current) await db.update(saleSettings).set({ companySignatureUrl: url, updatedByUserId: ctx.user.id }).where(eq(saleSettings.id, current.id)); else await db.insert(saleSettings).values({ companySignatureUrl: url, updatedByUserId: ctx.user.id }); await audit(ctx.user.id, "Signature mise à jour", "Entreprise", null, `Signature ou cachet ${input.filename} enregistré`); return { url }; }),
  }),
  remuneration: router({
    list: adminProcedure.query(async () => (await dbOrThrow()).select().from(remunerationProfiles).orderBy(desc(remunerationProfiles.updatedAt))),
    save: adminProcedure.input(z.object({ beneficiaryType: z.enum(["user", "agent"]), beneficiaryId: z.number().int().positive(), remunerationMode: z.enum(["fixed", "commission", "fixed_plus_commission"]), fixedMonthlyCents: z.number().int().min(0), commissionBasis: z.enum(["revenue", "net_profit"]), rateBasisPoints: z.number().int().min(0).max(10000), active: z.boolean() })).mutation(async ({ ctx, input }) => { const db = await dbOrThrow(); const current = (await db.select().from(remunerationProfiles)).find(item => item.beneficiaryType === input.beneficiaryType && item.beneficiaryId === input.beneficiaryId); if (current) await db.update(remunerationProfiles).set(input).where(eq(remunerationProfiles.id, current.id)); else await db.insert(remunerationProfiles).values(input); await audit(ctx.user.id, "Rémunération configurée", "Agent", input.beneficiaryId, "Profil de rémunération mis à jour"); return { success: true }; }),
  }),
  sales: router({
    list: protectedProcedure.query(() => listSales()),
    detail: protectedProcedure.input(z.object({ id: z.number().int().positive() })).query(async ({ input }) => { const db = await dbOrThrow(); const sale = (await db.select().from(sales).where(eq(sales.id, input.id)).limit(1))[0]; if (!sale) throw new TRPCError({ code: "NOT_FOUND", message: "Facture introuvable." }); const [customer, items, payments, commissions, seller, salesAgent, cashier] = await Promise.all([sale.customerId ? (await db.select().from(customers).where(eq(customers.id, sale.customerId)).limit(1))[0] ?? null : null, db.select().from(saleItems).where(eq(saleItems.saleId, sale.id)), db.select().from(salePayments).where(eq(salePayments.saleId, sale.id)), db.select().from(saleCommissions).where(eq(saleCommissions.saleId, sale.id)), (await db.select().from(users).where(eq(users.id, sale.sellerUserId)).limit(1))[0] ?? null, sale.salesAgentId ? (await db.select().from(agents).where(eq(agents.id, sale.salesAgentId)).limit(1))[0] ?? null : null, sale.cashierId ? (await db.select().from(agents).where(eq(agents.id, sale.cashierId)).limit(1))[0] ?? null : null]); return { sale, customer, items, payments, commissions, participants: { seller: seller ? { id: seller.id, name: seller.name || seller.email || "Vendeur", role: "Vendeur" } : null, salesAgent: salesAgent ? { id: salesAgent.id, name: salesAgent.name, role: "Agent commercial" } : null, cashier: cashier ? { id: cashier.id, name: cashier.name, role: "Caissier" } : null } }; }),
    create: protectedProcedure.input(z.object({ customerId: z.number().int().positive(), salesAgentId: z.number().int().positive().nullable(), cashierId: z.number().int().positive().nullable(), paymentMethod: z.enum(["cash", "card", "mobile_money", "bank_transfer", "credit"]), note: z.string().trim().max(1000).nullable(), items: z.array(z.object({ productId: z.number().int().positive(), quantity: z.number().int().positive() })).min(1) })).mutation(async ({ ctx, input }) => {
      const db = await dbOrThrow();
      const invoiceNumber = `FAC-${new Date().toISOString().slice(0, 10).replaceAll("-", "")}-${Date.now().toString().slice(-7)}`;
      await db.transaction(async tx => {
        const [customer] = await tx.select().from(customers).where(eq(customers.id, input.customerId)).limit(1);
        if (!customer) throw new TRPCError({ code: "NOT_FOUND", message: "Client introuvable." });
        const settings = (await tx.select().from(saleSettings).limit(1))[0];
        const salesAgentId = input.salesAgentId ?? settings?.defaultSalesAgentId ?? null;
        const cashierId = input.cashierId ?? settings?.defaultCashierId ?? null;
        if (settings?.requireSalesAgent && !salesAgentId) throw new TRPCError({ code: "BAD_REQUEST", message: "Un agent commercial est requis pour cette vente." });
        if (settings?.requireCashier && !cashierId) throw new TRPCError({ code: "BAD_REQUEST", message: "Un caissier est requis pour cette vente." });
        const associatedIds = [salesAgentId, cashierId].filter((id): id is number => id !== null);
        const selectedAgents = associatedIds.length ? await tx.select().from(agents).where(inArray(agents.id, associatedIds)) : [];
        if (salesAgentId && !selectedAgents.some(agent => agent.id === salesAgentId && agent.type === "sales_agent" && agent.active)) throw new TRPCError({ code: "BAD_REQUEST", message: "Agent commercial invalide." });
        if (cashierId && !selectedAgents.some(agent => agent.id === cashierId && agent.type === "cashier" && agent.active)) throw new TRPCError({ code: "BAD_REQUEST", message: "Caissier invalide." });
        const productIds = input.items.map(item => item.productId);
        const productRows = await tx.select().from(products).where(inArray(products.id, productIds));
        if (productRows.length !== productIds.length) throw new TRPCError({ code: "NOT_FOUND", message: "Un produit de la vente est introuvable." });
        const tierRows = productIds.length ? await tx.select().from(productPriceTiers).where(inArray(productPriceTiers.productId, productIds)) : [];
        const lines = input.items.map(item => { const product = productRows.find(row => row.id === item.productId)!; const isWholesale = customer.type === "wholesale"; const basePriceCents = priceForCustomer(customer.type, product.retailPriceCents, product.wholesalePriceCents); const unitPriceCents = priceForQuantityTier(basePriceCents, item.quantity, tierRows.filter(tier => tier.productId === product.id && tier.customerType === (isWholesale ? "wholesale" : "retail"))); const lineTotalCents = unitPriceCents * item.quantity; const lineCostCents = product.purchasePriceCents * item.quantity; const resultingQuantity = resultingStock(product.quantity, "exit", item.quantity); return { product, quantity: item.quantity, unitPriceCents, lineTotalCents, lineCostCents, resultingQuantity }; });
        const totalCents = lines.reduce((sum, line) => sum + line.lineTotalCents, 0); const totalCostCents = lines.reduce((sum, line) => sum + line.lineCostCents, 0); const netProfitCents = totalCents - totalCostCents;
        const result = await tx.insert(sales).values({ invoiceNumber, channel: "invoice", customerId: customer.id, sellerUserId: ctx.user.id, salesAgentId, cashierId, paymentMethod: input.paymentMethod, status: "paid", amountPaidCents: totalCents, subtotalCents: totalCents, totalCents, totalCostCents, netProfitCents, note: input.note });
        const saleId = Number(result[0].insertId);
        for (const line of lines) { await tx.insert(saleItems).values({ saleId, productId: line.product.id, productName: line.product.name, productReference: line.product.reference, quantity: line.quantity, unitPriceCents: line.unitPriceCents, purchasePriceCents: line.product.purchasePriceCents, lineTotalCents: line.lineTotalCents, lineCostCents: line.lineCostCents }); await tx.update(products).set({ quantity: line.resultingQuantity }).where(eq(products.id, line.product.id)); await tx.insert(stockMovements).values({ productId: line.product.id, type: "exit", quantity: signedMovementQuantity("exit", line.quantity), previousQuantity: line.product.quantity, resultingQuantity: line.resultingQuantity, reason: `Vente ${invoiceNumber}`, createdByUserId: ctx.user.id }); const existingAlert = (await tx.select().from(stockAlerts).where(eq(stockAlerts.productId, line.product.id)).limit(1))[0]; if (line.resultingQuantity <= line.product.minimumQuantity) { if (existingAlert) await tx.update(stockAlerts).set({ threshold: line.product.minimumQuantity, observedQuantity: line.resultingQuantity, status: "active", resolvedAt: null }).where(eq(stockAlerts.id, existingAlert.id)); else await tx.insert(stockAlerts).values({ productId: line.product.id, threshold: line.product.minimumQuantity, observedQuantity: line.resultingQuantity }); } }
        const profiles = await tx.select().from(remunerationProfiles).where(eq(remunerationProfiles.active, true));
        const beneficiaries = [{ type: "user" as const, id: ctx.user.id }, ...(salesAgentId ? [{ type: "agent" as const, id: salesAgentId }] : []), ...(cashierId ? [{ type: "agent" as const, id: cashierId }] : [])];
        for (const beneficiary of beneficiaries) { const profile = profiles.find(item => item.beneficiaryType === beneficiary.type && item.beneficiaryId === beneficiary.id); if (profile) { const amount = commissionCents({ remunerationMode: profile.remunerationMode, commissionBasis: profile.commissionBasis, rateBasisPoints: profile.rateBasisPoints, invoiceRevenueCents: totalCents, invoiceNetProfitCents: netProfitCents }); if (amount > 0) await tx.insert(saleCommissions).values({ saleId, beneficiaryType: beneficiary.type, beneficiaryId: beneficiary.id, commissionBasis: profile.commissionBasis, rateBasisPoints: profile.rateBasisPoints, commissionCents: amount }); } }
        await tx.insert(auditLogs).values({ actorUserId: ctx.user.id, action: "Vente créée", entityType: "Facture", entityId: String(saleId), detail: `Facture ${invoiceNumber} créée pour ${customer.name}` });
      });
      return { success: true, invoiceNumber };
    }),
  }),
});
