import { TRPCError } from "@trpc/server";
import { desc, eq } from "drizzle-orm";
import { z } from "zod";
import { auditLogs, inventoryItems, inventorySessions, products, stockMovements } from "../../drizzle/schema";
import { getDb } from "../db";
import { adminProcedure, protectedProcedure, router } from "../_core/trpc";
import { inventoryDifference, shouldCreateAdjustment } from "../inventoryRules";

async function dbOrThrow() { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Base de données indisponible." }); return db; }

export const inventoryRouter = router({
  list: protectedProcedure.query(async () => (await dbOrThrow()).select().from(inventorySessions).orderBy(desc(inventorySessions.createdAt))),
  detail: protectedProcedure.input(z.object({ id: z.number().int().positive() })).query(async ({ input }) => { const db = await dbOrThrow(); const session = (await db.select().from(inventorySessions).where(eq(inventorySessions.id, input.id)).limit(1))[0]; if (!session) throw new TRPCError({ code: "NOT_FOUND", message: "Inventaire introuvable." }); const items = await db.select({ id: inventoryItems.id, productId: products.id, productName: products.name, reference: products.reference, expectedQuantity: inventoryItems.expectedQuantity, countedQuantity: inventoryItems.countedQuantity }).from(inventoryItems).innerJoin(products, eq(inventoryItems.productId, products.id)).where(eq(inventoryItems.inventorySessionId, session.id)); return { session, items }; }),
  create: adminProcedure.input(z.object({ name: z.string().trim().min(2).max(160) })).mutation(async ({ ctx, input }) => { const db = await dbOrThrow(); const productRows = await db.select().from(products).orderBy(products.name); const result = await db.insert(inventorySessions).values({ name: input.name, createdByUserId: ctx.user.id }); const id = Number(result[0].insertId); if (productRows.length) await db.insert(inventoryItems).values(productRows.map(product => ({ inventorySessionId: id, productId: product.id, expectedQuantity: product.quantity }))); await db.insert(auditLogs).values({ actorUserId: ctx.user.id, action: "Inventaire créé", entityType: "Inventaire", entityId: String(id), detail: input.name }); return { id }; }),
  count: adminProcedure.input(z.object({ itemId: z.number().int().positive(), countedQuantity: z.number().int().min(0) })).mutation(async ({ input }) => { const db = await dbOrThrow(); await db.update(inventoryItems).set({ countedQuantity: input.countedQuantity }).where(eq(inventoryItems.id, input.itemId)); return { success: true }; }),
  validate: adminProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await dbOrThrow(); await db.transaction(async tx => { const session = (await tx.select().from(inventorySessions).where(eq(inventorySessions.id, input.id)).limit(1))[0]; if (!session || session.status === "validated") throw new TRPCError({ code: "BAD_REQUEST", message: "Inventaire non disponible." }); const items = await tx.select().from(inventoryItems).where(eq(inventoryItems.inventorySessionId, input.id)); for (const item of items) { if (item.countedQuantity === null) continue; const product = (await tx.select().from(products).where(eq(products.id, item.productId)).limit(1))[0]; if (!product || !shouldCreateAdjustment(product.quantity, item.countedQuantity)) continue; const difference = inventoryDifference(product.quantity, item.countedQuantity); await tx.update(products).set({ quantity: item.countedQuantity }).where(eq(products.id, product.id)); await tx.insert(stockMovements).values({ productId: product.id, type: "adjustment", quantity: difference, previousQuantity: product.quantity, resultingQuantity: item.countedQuantity, reason: `Inventaire ${session.name}`, createdByUserId: ctx.user.id }); } await tx.update(inventorySessions).set({ status: "validated", validatedByUserId: ctx.user.id, validatedAt: new Date() }).where(eq(inventorySessions.id, input.id)); await tx.insert(auditLogs).values({ actorUserId: ctx.user.id, action: "Inventaire validé", entityType: "Inventaire", entityId: String(input.id), detail: session.name }); }); return { success: true }; }),
});
