import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { displayCurrencyLabel, formatDate } from "@/lib/format";
import { ClipboardList, LockKeyhole } from "lucide-react";

export default function AuditLog() {
  const { user } = useAuth(); const isAdmin = user?.role === "admin"; const { data: logs = [], isLoading } = trpc.audit.list.useQuery(undefined, { enabled: isAdmin });
  if (!isAdmin) return <Restricted title="Journal des opérations" description="Le journal d’audit est réservé aux administrateurs de l’espace." />;
  return <div className="mx-auto max-w-[1400px] space-y-6"><header><p className="text-xs font-medium uppercase tracking-[0.16em] text-cyan-300">Conformité</p><h1 className="mt-2 text-2xl font-semibold tracking-tight text-white sm:text-3xl">Journal des opérations</h1><p className="mt-1.5 text-sm text-slate-400">Conservez une trace horodatée de chaque action structurante de l’espace stock.</p></header><Card className="border-white/[0.07] bg-[#111722] shadow-none"><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead className="bg-white/[0.018] text-[10px] font-semibold uppercase tracking-[0.13em] text-slate-500"><tr><th className="px-6 py-3">Action</th><th className="px-4 py-3">Détail</th><th className="px-4 py-3">Utilisateur</th><th className="px-6 py-3 text-right">Date</th></tr></thead><tbody className="divide-y divide-white/[0.06]">{isLoading ? <tr><td colSpan={4} className="px-6 py-12 text-center text-sm text-slate-500">Chargement du journal…</td></tr> : logs.length ? logs.map(log => <tr key={log.id} className="text-sm hover:bg-white/[0.018]"><td className="px-6 py-4"><Badge className="border-0 bg-cyan-400/10 text-cyan-300">{log.action}</Badge><p className="mt-1.5 text-xs text-slate-600">{log.entityType}</p></td><td className="max-w-md px-4 py-4 text-slate-400">{displayCurrencyLabel(log.detail || "—")}</td><td className="px-4 py-4"><p className="text-slate-200">{log.actorName || "Utilisateur supprimé"}</p><p className="mt-0.5 text-xs text-slate-600">{log.actorEmail || "—"}</p></td><td className="px-6 py-4 text-right text-xs text-slate-500">{formatDate(log.createdAt, true)}</td></tr>) : <tr><td colSpan={4} className="px-6 py-16 text-center text-sm text-slate-500">Aucune action à afficher pour le moment.</td></tr>}</tbody></table></div></CardContent></Card></div>;
}

export function Restricted({ title, description }: { title: string; description: string }) { return <div className="mx-auto grid min-h-[65vh] max-w-xl place-items-center text-center"><div><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-violet-400/10 text-violet-300"><LockKeyhole className="h-6 w-6" /></span><h1 className="mt-5 text-2xl font-semibold text-white">{title}</h1><p className="mt-2 text-sm leading-6 text-slate-400">{description}</p></div></div>; }
