import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { formatCurrency, formatDate } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Building2, Edit3, FilePlus2, FileText, Mail, MapPin, Phone, ReceiptText, Trash2, UsersRound, WalletCards } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { useLocation, useRoute } from "wouter";

type CustomerForm = { name: string; type: "ordinary" | "wholesale"; email: string; phone: string; address: string; taxNumber: string; notes: string };
type Customer = { id: number; name: string; type: "ordinary" | "wholesale"; email: string | null; phone: string | null; address: string | null; taxNumber: string | null; notes: string | null };
type Invoice = { id: number; invoiceNumber: string; status: string; totalCents: number; amountPaidCents: number; createdAt: Date };

export default function CustomerDetail() {
  const [, params] = useRoute("/clients/:id");
  const [, setLocation] = useLocation();
  const { user } = useAuth();
  const customerId = Number(params?.id);
  const { data, isLoading } = trpc.commerce.customers.get.useQuery({ id: customerId }, { enabled: Number.isInteger(customerId) && customerId > 0 });
  const utils = trpc.useUtils();
  const [editOpen, setEditOpen] = useState(false);
  const canManage = user?.role === "admin" || user?.role === "seller";
  const update = trpc.commerce.customers.update.useMutation({ onSuccess: async () => { await Promise.all([utils.commerce.customers.get.invalidate({ id: customerId }), utils.commerce.customers.list.invalidate()]); setEditOpen(false); toast.success("Client mis à jour."); }, onError: error => toast.error(error.message) });
  const remove = trpc.commerce.customers.remove.useMutation({ onSuccess: async () => { await utils.commerce.customers.list.invalidate(); toast.success("Client supprimé."); setLocation("/clients"); }, onError: error => toast.error(error.message) });
  if (isLoading) return <div className="mx-auto max-w-[1500px] py-24 text-center text-sm text-slate-500">Chargement de la fiche client…</div>;
  if (!data) return <MissingCustomer onBack={() => setLocation("/clients")} />;
  const customer = data.customer as Customer;
  const invoices = data.invoices as Invoice[];
  const summary = data.summary;
  const phoneDigits = (customer.phone || "").replace(/[^\d]/g, "");
  return <div className="mx-auto max-w-[1500px] space-y-6">
    <Button variant="ghost" onClick={() => setLocation("/clients")} className="-ml-3 text-primary hover:text-primary"><ArrowLeft className="mr-2 h-4 w-4" />Retour aux clients</Button>
    <section className="rounded-2xl border border-white/[0.07] bg-[#111722] p-5 shadow-sm sm:p-6"><div className="flex min-w-0 items-start gap-4"><span className={`grid h-14 w-14 shrink-0 place-items-center rounded-2xl ${customer.type === "wholesale" ? "bg-violet-400/10 text-violet-300" : "bg-primary/10 text-primary"}`}>{customer.type === "wholesale" ? <Building2 className="h-7 w-7" /> : <UsersRound className="h-7 w-7" />}</span><div className="min-w-0 flex-1"><p className="text-xs font-medium uppercase tracking-[0.16em] text-primary">Client {customer.type === "wholesale" ? "grossiste" : "détail"}</p><div className="mt-1 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><h1 className="truncate text-2xl font-semibold tracking-tight text-white sm:text-3xl">{customer.name}</h1><p className="mt-2 text-sm text-slate-400">{customer.address || "Adresse non renseignée"}</p></div>{canManage && <div className="flex shrink-0 flex-wrap gap-2"><Button onClick={() => setLocation(`/factures/nouvelle?client=${customer.id}`)} className="bg-primary text-primary-foreground hover:bg-primary/90"><FilePlus2 className="mr-2 h-4 w-4" />Nouvelle facture</Button><Button onClick={() => setEditOpen(true)} variant="outline" className="border-white/10 text-slate-300 hover:border-primary/40 hover:bg-primary/[0.06] hover:text-primary"><Edit3 className="mr-2 h-4 w-4" />Modifier</Button><Button variant="outline" onClick={() => { if (window.confirm(`Supprimer ${customer.name} ?`)) remove.mutate({ id: customer.id }); }} disabled={remove.isPending} className="border-rose-400/30 text-rose-300 hover:bg-rose-400/10 hover:text-rose-200"><Trash2 className="mr-2 h-4 w-4" />Supprimer</Button></div>}</div></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Info label="Téléphone" value={customer.phone || "Non renseigné"} icon={<Phone className="h-4 w-4" />} /><Info label="E-mail" value={customer.email || "Non renseigné"} icon={<Mail className="h-4 w-4" />} /><Info label="Numéro fiscal" value={customer.taxNumber || "Non renseigné"} icon={<WalletCards className="h-4 w-4" />} /><Info label="Tarif appliqué" value={customer.type === "wholesale" ? "Prix de gros" : "Prix détail"} icon={<ReceiptText className="h-4 w-4" />} /></div><div className="mt-5 flex flex-wrap gap-2 border-t border-white/[0.07] pt-5"><ContactButton label="Appeler" icon={<Phone className="h-4 w-4" />} href={customer.phone ? `tel:${customer.phone}` : undefined} /><ContactButton label="Message" icon={<ReceiptText className="h-4 w-4" />} href={phoneDigits ? `sms:${phoneDigits}` : undefined} /><ContactButton label="Mail" icon={<Mail className="h-4 w-4" />} href={customer.email ? `mailto:${customer.email}` : undefined} /></div></section>
    <CustomerNotes notes={customer.notes} />
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(340px,.8fr)]"><section><Card className="border-white/[0.07] bg-[#111722] shadow-none"><CardContent className="p-5 sm:p-6"><div className="flex items-center gap-2"><FileText className="h-5 w-5 text-primary" /><h2 className="text-lg font-semibold text-white">Historique des factures</h2></div>{invoices.length ? <div className="mt-5 space-y-2">{invoices.map(invoice => <button key={invoice.id} type="button" onClick={() => setLocation(`/factures?facture=${invoice.id}`)} className="flex w-full items-center justify-between gap-3 rounded-xl border border-white/[0.07] bg-white/[0.02] p-4 text-left transition hover:border-primary/40 hover:bg-primary/[0.04]"><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-100">{invoice.invoiceNumber}</p><p className="mt-1 text-xs text-slate-500">{formatDate(invoice.createdAt)} · {invoice.status === "paid" ? "Encaissée" : invoice.status === "partial" ? "Partielle" : "En attente"}</p></div><div className="shrink-0 text-right"><p className="text-sm font-semibold text-slate-100">{formatCurrency(invoice.totalCents)}</p>{invoice.amountPaidCents < invoice.totalCents && <p className="mt-1 text-xs font-medium text-amber-300">Reste {formatCurrency(invoice.totalCents - invoice.amountPaidCents)}</p>}</div></button>)}</div> : <Empty text="Aucune facture n’est encore liée à ce client." />}</CardContent></Card></section><aside className="space-y-6"><Metric label="Chiffre d’affaires" value={formatCurrency(summary.totalSalesCents)} tone="primary" /><Metric label="Solde à encaisser" value={formatCurrency(summary.outstandingCents)} tone={summary.outstandingCents > 0 ? "warning" : "success"} /><Metric label="Factures" value={String(summary.invoiceCount)} tone="default" /><Metric label="Dernière facture" value={summary.lastInvoiceAt ? formatDate(summary.lastInvoiceAt) : "Aucune"} tone="default" /></aside></div>
    <CustomerEditDialog customer={customer} open={editOpen} pending={update.isPending} onOpenChange={setEditOpen} onConfirm={form => update.mutate({ id: customer.id, name: form.name.trim(), otherReference: null, type: form.type, email: form.email.trim() || null, phone: form.phone.trim() || null, address: form.address.trim() || null, taxNumber: form.taxNumber.trim() || null, notes: form.notes.trim() || null })} />
  </div>;
}

function CustomerEditDialog({ customer, open, pending, onOpenChange, onConfirm }: { customer: Customer; open: boolean; pending: boolean; onOpenChange: (open: boolean) => void; onConfirm: (form: CustomerForm) => void }) { const [form, setForm] = useState<CustomerForm>(toForm(customer)); useEffect(() => { if (open) setForm(toForm(customer)); }, [customer, open]); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto border-white/10 bg-[#141b27] text-slate-100"><DialogHeader><DialogTitle>Modifier le client</DialogTitle></DialogHeader><div className="grid gap-4 py-2"><Field label="Nom *"><Input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} /></Field><Field label="Type"><Select value={form.type} onValueChange={value => setForm({ ...form, type: value as CustomerForm["type"] })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ordinary">Ordinaire · prix détail</SelectItem><SelectItem value="wholesale">Grossiste · prix gros</SelectItem></SelectContent></Select></Field><Field label="Adresse"><Input value={form.address} onChange={event => setForm({ ...form, address: event.target.value })} /></Field><Field label="E-mail"><Input type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} /></Field><Field label="Téléphone"><Input value={form.phone} onChange={event => setForm({ ...form, phone: event.target.value })} /></Field><Field label="Numéro fiscal"><Input value={form.taxNumber} onChange={event => setForm({ ...form, taxNumber: event.target.value })} /></Field><Field label="Notes"><Textarea value={form.notes} onChange={event => setForm({ ...form, notes: event.target.value })} /></Field></div><DialogFooter><Button variant="ghost" onClick={() => onOpenChange(false)}>Annuler</Button><Button disabled={pending || !form.name.trim()} onClick={() => onConfirm(form)} className="bg-primary text-primary-foreground hover:bg-primary/90">Enregistrer</Button></DialogFooter></DialogContent></Dialog>; }
function toForm(customer: Customer): CustomerForm { return { name: customer.name, type: customer.type, email: customer.email || "", phone: customer.phone || "", address: customer.address || "", taxNumber: customer.taxNumber || "", notes: customer.notes || "" }; }
function ContactButton({ label, icon, href }: { label: string; icon: React.ReactNode; href?: string }) { return <Button variant="outline" disabled={!href} asChild={Boolean(href)} className="border-white/10 text-slate-300 hover:border-primary/40 hover:bg-primary/[0.06] hover:text-primary disabled:opacity-45">{href ? <a href={href}>{icon}<span className="ml-2">{label}</span></a> : <span>{icon}<span className="ml-2">{label}</span></span>}</Button>; }
function Info({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) { return <div className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-3"><p className="flex items-center gap-2 text-[10px] font-medium uppercase tracking-[0.11em] text-slate-500">{icon}{label}</p><p className="mt-1 truncate text-sm font-medium text-slate-200">{value}</p></div>; }
function CustomerNotes({ notes }: { notes: string | null }) { return <Card className="border-white/[0.07] bg-[#111722] shadow-none"><CardContent className="p-5 sm:p-6"><div className="flex items-center gap-2"><MapPin className="h-5 w-5 text-primary" /><h2 className="text-base font-semibold text-white">Informations complémentaires</h2></div><p className="mt-4 whitespace-pre-line text-sm leading-relaxed text-slate-400">{notes || "Aucune note enregistrée."}</p></CardContent></Card>; }
function Metric({ label, value, tone }: { label: string; value: string; tone: "primary" | "success" | "warning" | "default" }) { const style = tone === "success" ? "text-emerald-300" : tone === "warning" ? "text-amber-300" : tone === "primary" ? "text-primary" : "text-slate-100"; return <Card className="border-white/[0.07] bg-[#111722] shadow-none"><CardContent className="p-5"><p className="text-xs text-slate-500">{label}</p><p className={`mt-2 text-xl font-semibold ${style}`}>{value}</p></CardContent></Card>; }
function Empty({ text }: { text: string }) { return <div className="mt-5 rounded-xl border border-dashed border-white/10 px-4 py-10 text-center text-sm text-slate-500">{text}</div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label className="text-xs text-slate-300">{label}</Label>{children}</div>; }
function MissingCustomer({ onBack }: { onBack: () => void }) { return <div className="mx-auto max-w-[1500px] space-y-5"><Button variant="ghost" onClick={onBack} className="text-primary"><ArrowLeft className="mr-2 h-4 w-4" />Retour aux clients</Button><Card className="border-dashed border-white/10 bg-[#111722] shadow-none"><CardContent className="py-16 text-center"><UsersRound className="mx-auto h-7 w-7 text-slate-600" /><p className="mt-4 font-medium text-slate-300">Client introuvable</p></CardContent></Card></div>; }
