import { ImportExportControls } from "@/components/ImportExportControls";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useAuth } from "@/_core/hooks/useAuth";
import type { CsvRow } from "@/lib/csv";
import { trpc } from "@/lib/trpc";
import { FileSpreadsheet, Package, Truck, UsersRound } from "lucide-react";

const toCents = (value: string | undefined) => Math.round(Number((value || "0").replace(/\s/g, "").replace(",", ".")) * 100);

export default function DataExchange() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const { data: products = [] } = trpc.products.list.useQuery();
  const { data: suppliers = [] } = trpc.suppliers.list.useQuery();
  const { data: customers = [] } = trpc.commerce.customers.list.useQuery();
  const createProduct = trpc.products.create.useMutation();
  const createSupplier = trpc.suppliers.create.useMutation();
  const createCustomer = trpc.commerce.customers.create.useMutation();
  const importProducts = async (rows: CsvRow[]) => { let imported = 0; const errors: string[] = []; for (let index = 0; index < rows.length; index += 1) { const row = rows[index]; try { const reference = row.reference?.trim(); const name = row.name?.trim(); if (!reference || !name || !row.category || !row.unit) throw new Error("référence, nom, catégorie et unité requis"); const quantity = Number(row.quantity || 0); const minimumQuantity = Number(row.minimum_quantity || row.minimumquantity || 0); if (!Number.isInteger(quantity) || !Number.isInteger(minimumQuantity)) throw new Error("quantités entières requises"); await createProduct.mutateAsync({ reference, name, description: row.description || null, category: row.category, unit: row.unit, purchasePriceCents: toCents(row.purchase_price || row.purchaseprice), retailPriceCents: toCents(row.retail_price || row.retailprice), wholesalePriceCents: toCents(row.wholesale_price || row.wholesaleprice), quantity, minimumQuantity, supplierId: row.supplier_id ? Number(row.supplier_id) : null, retailPriceTiers: [], wholesalePriceTiers: [] }); imported += 1; } catch (error) { errors.push(`ligne ${index + 2} — ${error instanceof Error ? error.message : "invalide"}`); } } utils.products.list.invalidate(); return { imported, errors }; };
  const importSuppliers = async (rows: CsvRow[]) => { let imported = 0; const errors: string[] = []; for (let index = 0; index < rows.length; index += 1) { const row = rows[index]; try { const name = row.name?.trim(); if (!name) throw new Error("nom requis"); await createSupplier.mutateAsync({ name, address: row.address || null, email: row.email || null, phone: row.phone || null, taxNumber: row.tax_number || row.taxnumber || null, otherReference: row.other_reference || row.otherreference || null, notes: row.notes || null }); imported += 1; } catch (error) { errors.push(`ligne ${index + 2} — ${error instanceof Error ? error.message : "invalide"}`); } } utils.suppliers.list.invalidate(); return { imported, errors }; };
  const importCustomers = async (rows: CsvRow[]) => { let imported = 0; const errors: string[] = []; for (let index = 0; index < rows.length; index += 1) { const row = rows[index]; try { const name = row.name?.trim(); if (!name) throw new Error("nom requis"); await createCustomer.mutateAsync({ name, type: ["wholesale", "grossiste"].includes(row.type?.toLowerCase()) ? "wholesale" : "ordinary", address: row.address || null, email: row.email || null, phone: row.phone || null, taxNumber: row.tax_number || row.taxnumber || null, otherReference: row.other_reference || row.otherreference || null, notes: row.notes || null }); imported += 1; } catch (error) { errors.push(`ligne ${index + 2} — ${error instanceof Error ? error.message : "invalide"}`); } } utils.commerce.customers.list.invalidate(); return { imported, errors }; };
  if (user?.role !== "admin") return <div className="mx-auto max-w-3xl py-20 text-center text-slate-400">Cette fonctionnalité est réservée aux administrateurs.</div>;
  return <div className="mx-auto max-w-5xl space-y-6"><header><p className="text-xs font-medium uppercase tracking-[0.16em] text-primary">Outils</p><h1 className="mt-2 text-2xl font-semibold tracking-tight text-white sm:text-3xl">Import & export</h1></header><div className="grid gap-4 md:grid-cols-3"><ExchangeCard icon={<Package className="h-5 w-5" />} title="Produits" count={products.length} controls={<ImportExportControls filename="produits.csv" headers={["reference", "name", "description", "category", "unit", "purchase_price", "retail_price", "wholesale_price", "quantity", "minimum_quantity", "supplier_id"]} rows={products.map(product => [product.reference, product.name, product.description, product.category, product.unit, product.purchasePriceCents / 100, product.retailPriceCents / 100, product.wholesalePriceCents / 100, product.quantity, product.minimumQuantity, product.supplierId])} onImport={importProducts} />} /><ExchangeCard icon={<Truck className="h-5 w-5" />} title="Fournisseurs" count={suppliers.length} controls={<ImportExportControls filename="fournisseurs.csv" headers={["name", "address", "email", "phone", "tax_number", "other_reference", "notes"]} rows={suppliers.map(supplier => [supplier.name, supplier.address, supplier.email, supplier.phone, supplier.taxNumber, supplier.otherReference, supplier.notes])} onImport={importSuppliers} />} /><ExchangeCard icon={<UsersRound className="h-5 w-5" />} title="Clients" count={customers.length} controls={<ImportExportControls filename="clients.csv" headers={["name", "type", "address", "email", "phone", "tax_number", "other_reference", "notes"]} rows={customers.map(customer => [customer.name, customer.type, customer.address, customer.email, customer.phone, customer.taxNumber, customer.otherReference, customer.notes])} onImport={importCustomers} />} /></div><Card className="border-primary/20 bg-primary/[0.04]"><CardContent className="flex gap-3 p-4 text-sm text-slate-300"><FileSpreadsheet className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><p>Exportez d’abord une liste pour obtenir le modèle CSV attendu. Lors de l’import, les lignes invalides sont ignorées et signalées sans empêcher l’intégration des lignes valides.</p></CardContent></Card></div>;
}

function ExchangeCard({ icon, title, count, controls }: { icon: React.ReactNode; title: string; count: number; controls: React.ReactNode }) { return <Card className="border-white/[0.07] bg-[#111722] shadow-none"><CardHeader className="pb-3"><span className="mb-3 grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary">{icon}</span><CardTitle className="text-base text-white">{title}</CardTitle><p className="text-xs text-slate-500">{count} entrée{count > 1 ? "s" : ""}</p></CardHeader><CardContent>{controls}</CardContent></Card>; }
