import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { formatCurrency, formatDate } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { CalendarDays, Pencil, Plus, ReceiptText, Trash2, WalletCards } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Restricted } from "./AuditLog";

const categories = [
  { value: "rent", label: "Loyer" }, { value: "energy", label: "Énergie" }, { value: "connection", label: "Connexion" }, { value: "salary", label: "Salaire" },
  { value: "marketing", label: "Marketing" }, { value: "supplies", label: "Fournitures" }, { value: "taxes", label: "Impôts" }, { value: "other", label: "Autre" },
] as const;
type ExpenseCategory = (typeof categories)[number]["value"];
type ExpenseForm = { category: ExpenseCategory; description: string; amount: string; spentAt: string };
const today = () => new Date().toISOString().slice(0, 10);
const blankForm = (): ExpenseForm => ({ category: "other", description: "", amount: "", spentAt: today() });
const categoryLabel = (category: string) => categories.find(item => item.value === category)?.label ?? "Autre";

export default function Expenses() {
  const { user } = useAuth(); const isAdmin = user?.role === "admin"; const utils = trpc.useUtils();
  const { data: expenses, isLoading } = trpc.expenses.list.useQuery(undefined, { enabled: isAdmin });
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<(NonNullable<typeof expenses>[number]) | null>(null); const [form, setForm] = useState<ExpenseForm>(blankForm);
  const create = trpc.expenses.create.useMutation({ onSuccess: () => { utils.expenses.list.invalidate(); utils.dashboard.get.invalidate(); toast.success("Dépense enregistrée."); close(); }, onError: error => toast.error(error.message) });
  const update = trpc.expenses.update.useMutation({ onSuccess: () => { utils.expenses.list.invalidate(); utils.dashboard.get.invalidate(); toast.success("Dépense mise à jour."); close(); }, onError: error => toast.error(error.message) });
  const remove = trpc.expenses.remove.useMutation({ onSuccess: () => { utils.expenses.list.invalidate(); utils.dashboard.get.invalidate(); toast.success("Dépense supprimée."); }, onError: error => toast.error(error.message) });
  const monthKey = new Date().toISOString().slice(0, 7);
  const monthlyTotal = useMemo(() => (expenses ?? []).filter(item => new Date(item.spentAt).toISOString().slice(0, 7) === monthKey).reduce((sum, item) => sum + item.amountCents, 0), [expenses, monthKey]);
  const allTotal = useMemo(() => (expenses ?? []).reduce((sum, item) => sum + item.amountCents, 0), [expenses]);
  const close = () => { setOpen(false); setEditing(null); setForm(blankForm()); };
  const beginCreate = () => { setEditing(null); setForm(blankForm()); setOpen(true); };
  const beginEdit = (expense: NonNullable<typeof expenses>[number]) => { setEditing(expense); setForm({ category: expense.category as ExpenseCategory, description: expense.description, amount: (expense.amountCents / 100).toFixed(2), spentAt: new Date(expense.spentAt).toISOString().slice(0, 10) }); setOpen(true); };
  const submit = () => { const amountCents = Math.round(Number(form.amount.replace(",", ".")) * 100); if (!form.description.trim() || !amountCents || !form.spentAt) return toast.error("Renseignez la description, le montant et la date."); const payload = { category: form.category, description: form.description.trim(), amountCents, spentAt: new Date(`${form.spentAt}T12:00:00`) }; if (editing) update.mutate({ id: editing.id, ...payload }); else create.mutate(payload); };
  if (!isAdmin) return <Restricted title="Dépenses" description="Le suivi des dépenses est réservé aux administrateurs." />;
  return <div className="mx-auto max-w-6xl space-y-6"><header className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h1 className="text-2xl font-semibold text-white sm:text-3xl">Dépenses</h1><Button onClick={beginCreate} className="bg-primary text-primary-foreground hover:bg-primary/90"><Plus className="mr-2 h-4 w-4" />Ajouter une dépense</Button></header><section className="grid gap-4 sm:grid-cols-3"><Metric icon={CalendarDays} label="Dépenses du mois" value={formatCurrency(monthlyTotal)} tone="primary" /><Metric icon={WalletCards} label="Dépenses enregistrées" value={formatCurrency(allTotal)} tone="amber" /><Metric icon={ReceiptText} label="Écritures" value={String(expenses?.length ?? 0)} tone="violet" /></section><Card className="border-white/[0.07] bg-[#111722]"><CardContent className="p-0"><div className="border-b border-white/[0.07] px-5 py-5"><p className="text-sm font-semibold text-white">Registre des dépenses</p></div>{isLoading ? <div className="space-y-3 p-5">{Array.from({ length: 4 }).map((_, index) => <Skeleton key={index} className="h-16 bg-white/10" />)}</div> : expenses?.length ? <div className="divide-y divide-white/[0.06]">{expenses.map(expense => <div key={expense.id} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><WalletCards className="h-4 w-4" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-medium text-slate-100">{expense.description}</p><span className="rounded-full bg-white/[0.07] px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-slate-400">{categoryLabel(expense.category)}</span></div><p className="mt-1 text-xs text-slate-500">{formatDate(expense.spentAt, true)}</p></div><p className="text-lg font-semibold text-rose-300">−{formatCurrency(expense.amountCents)}</p><div className="flex gap-1"><Button aria-label={`Modifier ${expense.description}`} onClick={() => beginEdit(expense)} variant="ghost" size="icon" className="text-primary hover:bg-primary/10"><Pencil className="h-4 w-4" /></Button><Button aria-label={`Supprimer ${expense.description}`} onClick={() => remove.mutate({ id: expense.id })} disabled={remove.isPending} variant="ghost" size="icon" className="text-rose-300 hover:bg-rose-400/10"><Trash2 className="h-4 w-4" /></Button></div></div>)}</div> : <div className="px-6 py-16 text-center"><WalletCards className="mx-auto h-7 w-7 text-slate-600" /><p className="mt-3 text-sm font-medium text-slate-300">Aucune dépense enregistrée</p><Button onClick={beginCreate} variant="ghost" className="mt-2 text-primary hover:bg-primary/10">Ajouter une première dépense</Button></div>}</CardContent></Card><ExpenseDialog open={open} form={form} setForm={setForm} editing={Boolean(editing)} pending={create.isPending || update.isPending} onClose={close} onSubmit={submit} /></div>;
}

function Metric({ icon: Icon, label, value, tone }: { icon: typeof CalendarDays; label: string; value: string; tone: "primary" | "amber" | "violet" }) { const colors = { primary: "bg-primary/10 text-primary", amber: "bg-amber-400/10 text-amber-300", violet: "bg-violet-400/10 text-violet-300" }; return <Card className="border-white/[0.07] bg-[#111722]"><CardContent className="flex items-start justify-between p-5"><div><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-xl font-semibold text-white">{value}</p></div><span className={`grid h-10 w-10 place-items-center rounded-xl ${colors[tone]}`}><Icon className="h-5 w-5" /></span></CardContent></Card>; }
function ExpenseDialog({ open, form, setForm, editing, pending, onClose, onSubmit }: { open: boolean; form: ExpenseForm; setForm: (form: ExpenseForm) => void; editing: boolean; pending: boolean; onClose: () => void; onSubmit: () => void }) { return <Dialog open={open} onOpenChange={value => !value && onClose()}><DialogContent className="border-white/10 bg-[#141b27] text-slate-100"><DialogHeader><DialogTitle>{editing ? "Modifier la dépense" : "Ajouter une dépense"}</DialogTitle></DialogHeader><div className="grid gap-4"><label className="grid gap-2 text-sm font-medium"><span>Catégorie</span><select value={form.category} onChange={event => setForm({ ...form, category: event.target.value as ExpenseCategory })} className="h-10 rounded-md border border-white/10 bg-white/[0.04] px-3 text-sm text-slate-100 outline-none focus:border-primary">{categories.map(category => <option key={category.value} value={category.value} className="bg-slate-900">{category.label}</option>)}</select></label><label className="grid gap-2 text-sm font-medium"><span>Description</span><Input value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} placeholder="Ex. Loyer du mois" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-medium"><span>Montant (FCFA)</span><Input type="number" min="0" step="0.01" value={form.amount} onChange={event => setForm({ ...form, amount: event.target.value })} placeholder="0" /></label><label className="grid gap-2 text-sm font-medium"><span>Date</span><Input type="date" value={form.spentAt} onChange={event => setForm({ ...form, spentAt: event.target.value })} /></label></div></div><DialogFooter><Button variant="outline" onClick={onClose} className="border-white/10 text-slate-200">Annuler</Button><Button onClick={onSubmit} disabled={pending} className="bg-primary text-primary-foreground hover:bg-primary/90">{pending ? "Enregistrement…" : "Enregistrer"}</Button></DialogFooter></DialogContent></Dialog>; }
