import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { formatCurrency, formatDate } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { Eye, Printer, ReceiptText, Share2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function Invoices() {
  const initial = Number(new URLSearchParams(window.location.search).get("facture")) || null;
  const [selectedId, setSelectedId] = useState<number | null>(initial); const [previewOpen, setPreviewOpen] = useState(false);
  const { data: sales = [], isLoading } = trpc.commerce.sales.list.useQuery(); const { data: detail } = trpc.commerce.sales.detail.useQuery({ id: selectedId ?? 0 }, { enabled: Boolean(selectedId) });
  const select = (id: number) => { setSelectedId(id); window.history.replaceState({}, "", `/factures?facture=${id}`); };
  const share = async () => { if (!detail) return; const url = `${window.location.origin}/factures?facture=${detail.sale.id}`; if (navigator.share) { try { await navigator.share({ title: `Facture ${detail.sale.invoiceNumber}`, text: `Consultez la facture ${detail.sale.invoiceNumber} dans StockPilot.`, url }); } catch { /* fermeture native sans action */ } } else { await navigator.clipboard.writeText(url); toast.success("Lien sécurisé de la facture copié."); } };
  const printInvoice = () => { const source = document.getElementById("invoice-print"); if (!source) return toast.error("Sélectionnez une facture avant de l’imprimer."); const popup = window.open("", "stockpilot-invoice", "width=900,height=700"); if (!popup) { toast.error("Autorisez les fenêtres surgissantes puis réessayez l’impression."); return; } popup.document.write(`<!doctype html><html><head><title>Facture StockPilot</title><style>body{font-family:Arial,sans-serif;color:#172033;padding:32px}*{box-sizing:border-box}.flex{display:flex}.justify-between{justify-content:space-between}.items-start{align-items:flex-start}.gap-4{gap:1rem}.grid{display:grid}.grid-cols-2{grid-template-columns:repeat(2,1fr)}.border-y,.border-t{border-color:#dbe3ea!important}.border-y{border-top:1px solid;border-bottom:1px solid}.border-t{border-top:1px solid}.py-4{padding-top:1rem;padding-bottom:1rem}.pt-4{padding-top:1rem}.mt-6{margin-top:1.5rem}.mt-5{margin-top:1.25rem}.mt-4{margin-top:1rem}.mt-3{margin-top:.75rem}.mt-2{margin-top:.5rem}.text-right{text-align:right}.text-center{text-align:center}.text-xl{font-size:1.25rem}.text-lg{font-size:1.125rem}.text-sm{font-size:.875rem}.text-xs{font-size:.75rem}.font-semibold{font-weight:600}.font-bold{font-weight:700}.uppercase{text-transform:uppercase}.tracking-\[0\.18em\]{letter-spacing:.18em}.text-slate-500,.text-slate-400{color:#64748b!important}.text-cyan-300,.text-cyan-200{color:#007b8b!important}.bg-white\/\[0\.025\]{background:#f5f8fa;padding:12px;border-radius:8px}.rounded-xl{border-radius:12px}.no-print{display:none!important}</style></head><body>${source.innerHTML}</body></html>`); popup.document.close(); popup.focus(); window.setTimeout(() => { popup.print(); popup.close(); }, 250); };
  return <div className="mx-auto max-w-[1450px] space-y-6"><header><p className="text-xs font-semibold uppercase tracking-[0.16em] text-cyan-300">Ventes</p><h1 className="mt-2 text-2xl font-semibold text-white sm:text-3xl">Factures</h1><p className="mt-1.5 text-sm text-slate-400">Prévisualisez, partagez et imprimez vos factures depuis un même espace sécurisé.</p></header><section className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_420px]"><Card className="border-white/[0.07] bg-[#111722]"><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-white/[0.018] text-[10px] uppercase tracking-[0.13em] text-slate-500"><tr><th className="px-6 py-3">Facture</th><th className="px-4 py-3">Client</th><th className="px-4 py-3">Vendeur</th><th className="px-4 py-3 text-right">Total</th><th className="px-5 py-3" /></tr></thead><tbody className="divide-y divide-white/[0.06]">{isLoading ? <tr><td colSpan={5} className="px-6 py-12 text-center text-slate-500">Chargement…</td></tr> : sales.length ? sales.map(sale => <tr key={sale.id} onClick={() => select(sale.id)} className={`cursor-pointer text-sm hover:bg-white/[0.025] ${selectedId === sale.id ? "bg-cyan-400/[0.05]" : ""}`}><td className="px-6 py-4"><p className="font-medium text-slate-200">{sale.invoiceNumber}</p><p className="mt-1 text-xs text-slate-500">{formatDate(sale.createdAt, true)}</p></td><td className="px-4 py-4"><p className="text-slate-300">{sale.customerName}</p><Badge className="mt-1 border-0 bg-white/[0.06] text-slate-400">{sale.customerType === "wholesale" ? "Gros" : "Détail"}</Badge></td><td className="px-4 py-4 text-slate-400">{sale.sellerName || "—"}</td><td className="px-4 py-4 text-right font-semibold text-slate-100">{formatCurrency(sale.totalCents)}</td><td className="px-5 py-4 text-right"><Button onClick={event => { event.stopPropagation(); select(sale.id); setPreviewOpen(true); }} variant="ghost" size="icon" className="text-cyan-300"><Eye className="h-4 w-4" /></Button></td></tr>) : <tr><td colSpan={5} className="px-6 py-16 text-center text-slate-500">Aucune facture créée.</td></tr>}</tbody></table></div></CardContent></Card><InvoicePreview detail={detail} onPrint={printInvoice} onShare={share} onPreview={() => setPreviewOpen(true)} /></section><Dialog open={previewOpen} onOpenChange={setPreviewOpen}><DialogContent className="max-h-[92vh] max-w-2xl overflow-y-auto border-white/10 bg-[#141b27] text-slate-100"><DialogHeader><DialogTitle>Aperçu de facture</DialogTitle></DialogHeader>{detail ? <InvoiceDocument detail={detail} /> : <p className="py-12 text-center text-sm text-slate-500">Chargement de la facture…</p>}</DialogContent></Dialog></div>;
}

function InvoicePreview({ detail, onPrint, onShare, onPreview }: { detail: any; onPrint: () => void; onShare: () => void; onPreview: () => void }) { if (!detail) return <Card className="h-fit border-white/[0.07] bg-[#111722]"><CardContent className="py-16 text-center"><ReceiptText className="mx-auto h-7 w-7 text-slate-600" /><p className="mt-3 text-sm text-slate-500">Sélectionnez une facture pour afficher son aperçu.</p></CardContent></Card>; return <Card className="h-fit border-white/[0.07] bg-[#111722]"><CardContent className="p-5"><div id="invoice-print"><InvoiceDocument detail={detail} /></div><div className="no-print mt-5 grid grid-cols-3 gap-2"><Button onClick={onPrint} variant="outline" className="border-white/10 text-slate-200"><Printer className="mr-2 h-4 w-4" />Imprimer</Button><Button onClick={onPreview} variant="outline" className="border-white/10 text-slate-200"><Eye className="mr-2 h-4 w-4" />Aperçu</Button><Button onClick={onShare} className="bg-cyan-400 text-slate-950"><Share2 className="mr-2 h-4 w-4" />Partager</Button></div><p className="no-print mt-3 text-center text-[10px] text-slate-500">Le lien ouvre cette facture uniquement pour les utilisateurs autorisés.</p></CardContent></Card>; }

function InvoiceDocument({ detail }: { detail: any }) { const participants = [detail.participants?.seller, detail.participants?.salesAgent, detail.participants?.cashier].filter(Boolean); return <div className="invoice-document"><header className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-cyan-300">StockPilot</p><h2 className="mt-2 text-xl font-semibold text-white">Facture</h2><p className="mt-1 text-xs text-slate-500">{detail.sale.invoiceNumber} · {formatDate(detail.sale.createdAt, true)}</p></div><Badge className="border-0 bg-emerald-400/10 text-emerald-300">{detail.sale.status === "paid" ? "Payée" : detail.sale.status}</Badge></header><div className="mt-6 grid grid-cols-2 gap-4 border-y border-white/[0.07] py-4 text-sm"><div><p className="text-xs text-slate-500">Facturé à</p><p className="mt-1 font-semibold text-slate-200">{detail.customer.name}</p><p className="mt-1 text-xs text-slate-500">{detail.customer.type === "wholesale" ? "Client grossiste" : "Client ordinaire"}</p></div><div className="text-right"><p className="text-xs text-slate-500">Mode de paiement</p><p className="mt-1 font-semibold capitalize text-slate-200">{detail.sale.paymentMethod.replaceAll("_", " ")}</p></div></div>{participants.length > 0 && <div className="mt-4 rounded-xl bg-white/[0.025] p-3"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">Intervenants de vente</p><div className="mt-3 grid gap-2">{participants.map((participant: any) => <div key={`${participant.role}-${participant.id}`} className="flex items-center justify-between text-xs"><span className="text-slate-500">{participant.role}</span><span className="font-semibold text-slate-200">{participant.name}</span></div>)}</div></div>}<div className="mt-4 space-y-3">{detail.items.map((item: any) => <div key={item.id} className="flex justify-between gap-3 text-sm"><span className="min-w-0"><span className="block truncate font-medium text-slate-200">{item.productName}</span><span className="text-xs text-slate-500">{item.quantity} × {formatCurrency(item.unitPriceCents)}</span></span><span className="font-semibold text-slate-100">{formatCurrency(item.lineTotalCents)}</span></div>)}</div><div className="mt-5 space-y-2 border-t border-white/[0.07] pt-4"><div className="flex justify-between text-sm text-slate-400"><span>Sous-total</span><span>{formatCurrency(detail.sale.subtotalCents)}</span></div><div className="flex justify-between text-xl font-semibold text-white"><span>Total</span><span className="text-cyan-200">{formatCurrency(detail.sale.totalCents)}</span></div></div><p className="mt-5 border-t border-white/[0.07] pt-4 text-center text-[10px] text-slate-500">Document généré par StockPilot · Merci pour votre confiance.</p></div>; }
