import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { formatCurrency, formatDate } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowLeft, CalendarCheck2, CalendarClock, CheckCircle2, ClipboardList, Edit3, Mail, MessageCircle, PackageCheck, Printer, RotateCcw, Send, Trash2, Truck } from "lucide-react";
import { jsPDF } from "jspdf";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { useLocation, useRoute } from "wouter";

type Status = "draft" | "sent" | "received" | "cancelled";
type OrderLine = { id: number; productName: string; productReference: string; unit: string; quantity: number; receivedQuantity: number; purchasePriceCents: number; lineTotalCents: number };
type Order = { id: number; orderNumber: string; supplierId: number; status: Status; subtotalCents: number; vatRateBasisPoints: number; vatCents: number; deliveryFeeCents: number; totalCents: number; notes: string | null; cancellationReason: string | null; expectedDeliveryDate: Date | null; receivedAt: Date | null; cancelledAt: Date | null; createdAt: Date; items: OrderLine[]; supplier: { name: string; email: string | null; phone: string | null; address: string | null } | null };

const statusMeta: Record<Status, { label: string; className: string }> = {
  draft: { label: "En attente", className: "border-amber-400/25 bg-amber-400/10 text-amber-200" },
  sent: { label: "Envoyé", className: "border-sky-400/25 bg-sky-400/10 text-sky-200" },
  received: { label: "Reçu", className: "border-emerald-400/25 bg-emerald-400/10 text-emerald-200" },
  cancelled: { label: "Annulé", className: "border-rose-400/25 bg-rose-400/10 text-rose-200" },
};

export default function PurchaseOrderDetail() {
  const [, params] = useRoute("/bons-commande/:id");
  const [, setLocation] = useLocation();
  const orderId = Number(params?.id);
  const returnToOrders = new URLSearchParams(window.location.search).get("origine") === "bons";
  const { user } = useAuth();
  const canManage = user?.role === "admin";
  const utils = trpc.useUtils();
  const { data, isLoading } = trpc.purchaseOrders.get.useQuery({ id: orderId }, { enabled: Number.isInteger(orderId) && orderId > 0 });
  const order = data as Order | undefined;
  const [editOpen, setEditOpen] = useState(false);
  const [receiveOpen, setReceiveOpen] = useState(false);
  const [cancelOpen, setCancelOpen] = useState(false);
  const refresh = async () => { if (order) await Promise.all([utils.purchaseOrders.get.invalidate({ id: order.id }), utils.purchaseOrders.listBySupplier.invalidate({ supplierId: order.supplierId }), utils.products.list.invalidate(), utils.movements.list.invalidate()]); };
  const update = trpc.purchaseOrders.updateDetails.useMutation({ onSuccess: async () => { await refresh(); setEditOpen(false); toast.success("Bon de commande mis à jour."); }, onError: error => toast.error(error.message) });
  const receive = trpc.purchaseOrders.receive.useMutation({ onSuccess: async result => { await refresh(); setReceiveOpen(false); toast.success(result.alreadyReceived ? "Ce bon est déjà entièrement reçu." : ("complete" in result && result.complete ? "Réception complète validée." : "Réception partielle enregistrée.")); }, onError: error => toast.error(error.message) });
  const cancel = trpc.purchaseOrders.cancel.useMutation({ onSuccess: async () => { await refresh(); setCancelOpen(false); toast.success("Bon de commande annulé."); }, onError: error => toast.error(error.message) });
  const remove = trpc.purchaseOrders.remove.useMutation({ onSuccess: () => { toast.success("Bon de commande supprimé."); if (order) setLocation(`/fournisseurs/${order.supplierId}`); }, onError: error => toast.error(error.message) });
  const markSent = trpc.purchaseOrders.markSent.useMutation({ onError: error => toast.error(error.message) });
  if (isLoading) return <div className="mx-auto max-w-[1500px] py-24 text-center text-sm text-slate-500">Chargement du bon de commande…</div>;
  if (!order) return <MissingOrder onBack={() => setLocation("/fournisseurs")} />;
  const expected = order.expectedDeliveryDate ? new Date(order.expectedDeliveryDate) : null;
  const today = new Date(); today.setHours(0, 0, 0, 0);
  const overdue = Boolean(expected && expected < today && order.status !== "received" && order.status !== "cancelled");
  const orderedCount = order.items.reduce((sum, line) => sum + line.quantity, 0);
  const receivedCount = order.items.reduce((sum, line) => sum + line.receivedQuantity, 0);
  const phone = (order.supplier?.phone || "").replace(/[^\d]/g, "");
  const message = buildMessage(order);
  const markOrderSent = () => markSent.mutate({ id: order.id }, { onSuccess: refresh });
  const shareWhatsapp = () => { if (!phone) return toast.error("Le numéro WhatsApp du fournisseur est indisponible."); const popup = window.open("", "_blank"); markSent.mutate({ id: order.id }, { onSuccess: async () => { await refresh(); const url = `https://wa.me/${phone}?text=${encodeURIComponent(message)}`; if (popup) popup.location.href = url; else window.location.assign(url); } }); };
  const shareEmail = async () => { if (!order.supplier?.email) return toast.error("L’adresse e-mail du fournisseur est indisponible."); const file = createPdf(order); if (navigator.canShare?.({ files: [file] })) { try { await navigator.share({ title: `Bon de commande ${order.orderNumber}`, text: message, files: [file] }); } catch { return; } } else { downloadFile(file); window.location.href = `mailto:${order.supplier.email}?subject=${encodeURIComponent(`Bon de commande ${order.orderNumber}`)}&body=${encodeURIComponent(`${message}\n\nLe PDF du bon est téléchargé : joignez-le à ce message.`)}`; toast.info("Le PDF est téléchargé. Joignez-le au message e-mail qui s’ouvre."); } markOrderSent(); };
  const actionable = order.status !== "received" && order.status !== "cancelled";
  const backPath = returnToOrders ? "/bons-commande" : `/fournisseurs/${order.supplierId}`;
  const backLabel = returnToOrders ? "Retour aux bons de commande" : "Retour au fournisseur";
  return <div className="mx-auto max-w-[1500px] space-y-6"><Button variant="ghost" onClick={() => setLocation(backPath)} className="-ml-3 text-primary hover:text-primary"><ArrowLeft className="mr-2 h-4 w-4" />{backLabel}</Button>
    <section className={`rounded-2xl border p-5 shadow-sm sm:p-6 ${overdue ? "border-rose-400/35 bg-rose-400/[0.05]" : "border-white/[0.07] bg-[#111722]"}`}><div className="flex min-w-0 items-start gap-4"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-primary/10 text-primary"><ClipboardList className="h-7 w-7" /></span><div className="min-w-0"><p className="text-xs font-medium uppercase tracking-[0.16em] text-primary">Bon de commande</p><div className="mt-1 flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold tracking-tight text-white sm:text-3xl">{order.orderNumber}</h1><StatusBadge status={order.status} /></div><p className="mt-2 text-sm text-slate-400">{order.supplier?.name || "Fournisseur indisponible"}</p></div></div>
      <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<CalendarClock className="h-4 w-4" />} label="Date de commande" value={formatDate(order.createdAt)} /><Metric icon={<Truck className="h-4 w-4" />} label="Livraison attendue" value={expected ? formatDate(expected) : "Non planifiée"} tone={overdue ? "danger" : "default"} /><Metric icon={<CalendarCheck2 className="h-4 w-4" />} label="Date de réception" value={order.receivedAt ? formatDate(order.receivedAt) : "Non reçue"} /><Metric icon={<PackageCheck className="h-4 w-4" />} label="Progression" value={`${receivedCount} / ${orderedCount} unités`} tone={receivedCount ? "success" : "default"} /></div>{overdue && <div className="mt-4 flex items-center gap-2 rounded-xl border border-rose-400/25 bg-rose-400/10 px-3 py-2 text-sm font-medium text-rose-200"><AlertTriangle className="h-4 w-4" />Livraison en retard depuis le {formatDate(expected!)}.</div>}</section>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(340px,.8fr)]"><Card className="border-white/[0.07] bg-[#111722] shadow-none"><CardContent className="p-5 sm:p-6"><div className="flex items-center gap-2"><Truck className="h-5 w-5 text-primary" /><h2 className="text-lg font-semibold text-white">Lignes commandées</h2></div><div className="mt-5 overflow-hidden rounded-xl border border-white/[0.07]"><div className="grid grid-cols-[minmax(0,1fr)_70px_90px] gap-3 border-b border-white/[0.07] bg-white/[0.025] px-4 py-3 text-[10px] font-medium uppercase tracking-[0.1em] text-slate-500 sm:grid-cols-[minmax(0,1fr)_100px_100px_110px]"><span>Produit</span><span className="text-right">Qté</span><span className="text-right">Reçu</span><span className="hidden text-right sm:block">Montant</span></div>{order.items.map(line => { const remaining = line.quantity - line.receivedQuantity; return <div key={line.id} className="grid grid-cols-[minmax(0,1fr)_70px_90px] gap-3 border-b border-white/[0.07] px-4 py-4 last:border-b-0 sm:grid-cols-[minmax(0,1fr)_100px_100px_110px]"><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-100">{line.productName}</p><p className="mt-1 text-xs text-slate-500">{line.productReference} · {line.unit} · Reste {remaining}</p></div><span className="text-right text-sm text-slate-300">{line.quantity}</span><span className="text-right text-sm font-semibold text-emerald-300">{line.receivedQuantity}</span><span className="hidden text-right text-sm text-slate-300 sm:block">{formatCurrency(line.lineTotalCents)}</span></div>; })}</div></CardContent></Card>
      <aside className="space-y-6"><Card className="border-white/[0.07] bg-[#111722] shadow-none"><CardContent className="p-5"><p className="text-[10px] font-medium uppercase tracking-[0.12em] text-slate-500">Montant commandé</p><p className="mt-2 text-2xl font-semibold text-white">{formatCurrency(order.totalCents)}</p><div className="mt-3 space-y-1 text-xs text-slate-400"><p>Sous-total : {formatCurrency(order.subtotalCents || 0)}</p>{order.vatCents > 0 && <p>TVA ({((order.vatRateBasisPoints || 0) / 100).toFixed(2)} %) : {formatCurrency(order.vatCents)}</p>}{order.deliveryFeeCents > 0 && <p>Frais de livraison : {formatCurrency(order.deliveryFeeCents)}</p>}</div><p className="mt-3 text-sm text-slate-400">{order.notes || "Aucune note ajoutée."}</p></CardContent></Card>{order.cancellationReason && <Card className="border-rose-400/25 bg-rose-400/[0.05] shadow-none"><CardContent className="p-5"><div className="flex items-center gap-2 text-rose-200"><AlertTriangle className="h-5 w-5" /><h2 className="font-semibold">Annulation</h2></div><p className="mt-3 text-sm text-rose-100/85">{order.cancellationReason}</p>{order.cancelledAt && <p className="mt-2 text-xs text-rose-200/70">Le {formatDate(order.cancelledAt)}</p>}</CardContent></Card>}</aside></div>
    {canManage && <div className="flex flex-col gap-3 border-t border-white/[0.07] pt-6"><div className="flex flex-wrap justify-end gap-2"><Button variant="outline" onClick={() => window.print()} className="border-white/10 text-slate-300 hover:bg-primary/[0.06] hover:text-primary"><Printer className="mr-2 h-4 w-4" />Imprimer</Button><Button variant="outline" onClick={shareWhatsapp} disabled={order.status === "cancelled" || markSent.isPending || !phone} className="border-white/10 text-slate-300 hover:bg-primary/[0.06] hover:text-primary"><MessageCircle className="mr-2 h-4 w-4" />WhatsApp</Button><Button variant="outline" onClick={shareEmail} disabled={order.status === "cancelled" || markSent.isPending || !order.supplier?.email} className="border-white/10 text-slate-300 hover:bg-primary/[0.06] hover:text-primary"><Send className="mr-2 h-4 w-4" />E-mail + PDF</Button>{actionable && <><Button onClick={() => setEditOpen(true)} className="bg-primary text-primary-foreground hover:bg-primary/90"><Edit3 className="mr-2 h-4 w-4" />Modifier</Button><Button onClick={() => setReceiveOpen(true)} className="bg-primary text-primary-foreground hover:bg-primary/90"><PackageCheck className="mr-2 h-4 w-4" />Réceptionner</Button><Button variant="outline" onClick={() => setCancelOpen(true)} className="border-rose-400/30 text-rose-300 hover:bg-rose-400/10"><Trash2 className="mr-2 h-4 w-4" />Annuler</Button></>}{(order.status === "draft" || order.status === "cancelled") && <Button variant="outline" onClick={() => { if (window.confirm(`Supprimer ${order.orderNumber} ?`)) remove.mutate({ id: order.id }); }} className="border-rose-400/30 text-rose-300 hover:bg-rose-400/10"><Trash2 className="mr-2 h-4 w-4" />Supprimer</Button>}</div>{order.status === "received" && <Button variant="outline" onClick={() => setLocation(backPath)} className="w-full border-white/10 text-slate-300 hover:bg-primary/[0.06] hover:text-primary"><RotateCcw className="mr-2 h-4 w-4" />{returnToOrders ? "Retourner aux bons de commande" : "Retourner au fournisseur"}</Button>}</div>}
    <OrderEditDialog order={order} open={editOpen} pending={update.isPending} onOpenChange={setEditOpen} onConfirm={values => update.mutate({ id: order.id, ...values })} />
    <ReceiptDialog order={order} open={receiveOpen} pending={receive.isPending} onOpenChange={setReceiveOpen} onConfirm={lines => receive.mutate({ id: order.id, lines })} />
    <CancelDialog order={order} open={cancelOpen} pending={cancel.isPending} onOpenChange={setCancelOpen} onConfirm={reason => cancel.mutate({ id: order.id, reason })} />
  </div>;
}

function OrderEditDialog({ order, open, pending, onOpenChange, onConfirm }: { order: Order; open: boolean; pending: boolean; onOpenChange: (open: boolean) => void; onConfirm: (values: { notes: string | null; expectedDeliveryDate: Date | null; deliveryFeeCents: number }) => void }) { const [notes, setNotes] = useState(order.notes || ""); const [date, setDate] = useState(toDateInput(order.expectedDeliveryDate)); const [deliveryFee, setDeliveryFee] = useState(String((order.deliveryFeeCents || 0) / 100)); useEffect(() => { if (open) { setNotes(order.notes || ""); setDate(toDateInput(order.expectedDeliveryDate)); setDeliveryFee(String((order.deliveryFeeCents || 0) / 100)); } }, [open, order]); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="border-white/10 bg-[#141b27] text-slate-100"><DialogHeader><DialogTitle>Modifier le bon {order.orderNumber}</DialogTitle></DialogHeader><div className="grid gap-4 py-2"><div><Label className="text-xs text-slate-300">Livraison attendue</Label><Input type="date" value={date} onChange={event => setDate(event.target.value)} className="mt-2 border-white/10 bg-[#0e141f]" /></div><div><Label htmlFor="edit-delivery-fee" className="text-xs text-slate-300">Frais de livraison</Label><Input id="edit-delivery-fee" type="number" min="0" step="1" value={deliveryFee} onChange={event => setDeliveryFee(event.target.value)} className="mt-2 border-white/10 bg-[#0e141f]" /></div><div><Label className="text-xs text-slate-300">Note</Label><Textarea value={notes} onChange={event => setNotes(event.target.value)} className="mt-2 min-h-28 border-white/10 bg-[#0e141f]" /></div></div><DialogFooter><Button variant="ghost" onClick={() => onOpenChange(false)}>Annuler</Button><Button disabled={pending} onClick={() => onConfirm({ notes: notes.trim() || null, expectedDeliveryDate: date ? new Date(`${date}T12:00:00`) : null, deliveryFeeCents: Math.max(0, Math.round((Number(deliveryFee) || 0) * 100)) })} className="bg-primary text-primary-foreground hover:bg-primary/90">Enregistrer</Button></DialogFooter></DialogContent></Dialog>; }
function ReceiptDialog({ order, open, pending, onOpenChange, onConfirm }: { order: Order; open: boolean; pending: boolean; onOpenChange: (open: boolean) => void; onConfirm: (lines: Array<{ id: number; quantity: number }>) => void }) { const [quantities, setQuantities] = useState<Record<number, number>>({}); useEffect(() => { if (open) setQuantities(Object.fromEntries(order.items.map(line => [line.id, line.quantity - line.receivedQuantity]))); }, [open, order]); const lines = order.items.map(line => ({ id: line.id, quantity: Math.max(0, Math.min(line.quantity - line.receivedQuantity, quantities[line.id] ?? 0)) })).filter(line => line.quantity > 0); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto border-white/10 bg-[#141b27] text-slate-100 sm:max-w-2xl"><DialogHeader><DialogTitle>Réception partielle · {order.orderNumber}</DialogTitle></DialogHeader><div className="space-y-3 py-2">{order.items.map(line => { const remaining = line.quantity - line.receivedQuantity; return <div key={line.id} className="grid gap-2 rounded-xl border border-white/[0.07] bg-white/[0.025] p-3 sm:grid-cols-[1fr_auto]"><div><p className="text-sm font-semibold text-slate-100">{line.productName}</p><p className="mt-1 text-xs text-slate-500">Commandé {line.quantity} · Déjà reçu {line.receivedQuantity} · Reste {remaining}</p></div><Input type="number" min="0" max={remaining} disabled={remaining === 0} value={quantities[line.id] ?? 0} onChange={event => setQuantities(current => ({ ...current, [line.id]: Number(event.target.value) || 0 }))} className="h-9 w-full border-white/10 bg-[#0e141f] text-right sm:w-24" /></div>; })}</div><DialogFooter><Button variant="ghost" onClick={() => onOpenChange(false)}>Annuler</Button><Button disabled={!lines.length || pending} onClick={() => onConfirm(lines)} className="bg-primary text-primary-foreground hover:bg-primary/90"><PackageCheck className="mr-2 h-4 w-4" />Valider la réception</Button></DialogFooter></DialogContent></Dialog>; }
function CancelDialog({ order, open, pending, onOpenChange, onConfirm }: { order: Order; open: boolean; pending: boolean; onOpenChange: (open: boolean) => void; onConfirm: (reason: string) => void }) { const [reason, setReason] = useState(""); useEffect(() => { if (open) setReason(""); }, [open]); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="border-white/10 bg-[#141b27] text-slate-100"><DialogHeader><DialogTitle>Annuler le bon {order.orderNumber}</DialogTitle></DialogHeader><div className="py-2"><Label className="text-xs text-slate-300">Motif d’annulation *</Label><Textarea value={reason} onChange={event => setReason(event.target.value)} placeholder="Expliquez la raison de l’annulation" className="mt-2 min-h-28 border-white/10 bg-[#0e141f]" /></div><DialogFooter><Button variant="ghost" onClick={() => onOpenChange(false)}>Retour</Button><Button disabled={pending || reason.trim().length < 3} onClick={() => onConfirm(reason.trim())} className="bg-rose-600 text-white hover:bg-rose-500"><Trash2 className="mr-2 h-4 w-4" />Confirmer l’annulation</Button></DialogFooter></DialogContent></Dialog>; }
function Metric({ icon, label, value, tone = "default" }: { icon: React.ReactNode; label: string; value: string; tone?: "default" | "danger" | "success" }) { const text = tone === "danger" ? "text-rose-200" : tone === "success" ? "text-emerald-200" : "text-slate-200"; return <div className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-3"><p className="flex items-center gap-2 text-[10px] font-medium uppercase tracking-[0.11em] text-slate-500">{icon}{label}</p><p className={`mt-1 truncate text-sm font-medium ${text}`}>{value}</p></div>; }
function StatusBadge({ status }: { status: Status }) { const meta = statusMeta[status]; return <span className={`rounded-full border px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.08em] ${meta.className}`}>{meta.label}</span>; }
function MissingOrder({ onBack }: { onBack: () => void }) { return <div className="mx-auto max-w-[1500px] space-y-5"><Button variant="ghost" onClick={onBack} className="text-primary"><ArrowLeft className="mr-2 h-4 w-4" />Retour aux fournisseurs</Button><Card className="border-dashed border-white/10 bg-[#111722] shadow-none"><CardContent className="py-16 text-center"><ClipboardList className="mx-auto h-7 w-7 text-slate-600" /><p className="mt-4 font-medium text-slate-300">Bon de commande introuvable</p></CardContent></Card></div>; }
function toDateInput(value: Date | null) { if (!value) return ""; const date = new Date(value); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
function buildMessage(order: Order) { return [`Bonjour ${order.supplier?.name || ""},`, "", `Veuillez trouver notre bon de commande ${order.orderNumber}.`, "", ...order.items.map(item => `• ${item.productName} (${item.productReference}) — ${item.quantity} ${item.unit}`), "", `Sous-total : ${formatCurrency(order.subtotalCents || 0)}`, order.vatCents > 0 ? `TVA (${((order.vatRateBasisPoints || 0) / 100).toFixed(2)} %) : ${formatCurrency(order.vatCents)}` : "", order.deliveryFeeCents > 0 ? `Frais de livraison : ${formatCurrency(order.deliveryFeeCents)}` : "", `Total TTC : ${formatCurrency(order.totalCents)}`, order.expectedDeliveryDate ? `Livraison attendue : ${formatDate(order.expectedDeliveryDate)}` : "", order.notes ? `Note : ${order.notes}` : "", "", "Merci."].filter(Boolean).join("\n"); }
function createPdf(order: Order) { const doc = new jsPDF({ unit: "pt", format: "a4" }); let y = 56; doc.setFontSize(20); doc.setTextColor(0, 123, 139); doc.text("Bon de commande", 44, y); y += 24; doc.setFontSize(10); doc.setTextColor(90, 101, 115); doc.text(`${order.orderNumber} · ${formatDate(order.createdAt)}`, 44, y); doc.text(order.supplier?.name || "", 552, 56, { align: "right" }); y += 38; doc.setDrawColor(0, 123, 139); doc.line(44, y, 552, y); y += 24; doc.setFontSize(9); doc.setTextColor(30, 41, 59); doc.text("Produit", 44, y); doc.text("Référence", 250, y); doc.text("Qté", 380, y); doc.text("Total", 552, y, { align: "right" }); y += 14; doc.setDrawColor(220, 229, 237); order.items.forEach(item => { if (y > 760) { doc.addPage(); y = 56; } doc.line(44, y, 552, y); y += 16; doc.text(item.productName, 44, y); doc.text(item.productReference, 250, y); doc.text(`${item.quantity} ${item.unit}`, 380, y); doc.text(formatCurrency(item.lineTotalCents), 552, y, { align: "right" }); y += 12; }); y += 20; doc.setFontSize(9); doc.setTextColor(90, 101, 115); doc.text(`Sous-total : ${formatCurrency(order.subtotalCents || 0)}`, 552, y, { align: "right" }); y += 14; if (order.vatCents > 0) { doc.text(`TVA (${((order.vatRateBasisPoints || 0) / 100).toFixed(2)} %) : ${formatCurrency(order.vatCents)}`, 552, y, { align: "right" }); y += 14; } if (order.deliveryFeeCents > 0) { doc.text(`Livraison : ${formatCurrency(order.deliveryFeeCents)}`, 552, y, { align: "right" }); y += 14; } doc.setFontSize(12); doc.setTextColor(15, 23, 42); doc.text(`Total TTC : ${formatCurrency(order.totalCents)}`, 552, y, { align: "right" }); return new File([doc.output("blob")], `${order.orderNumber}.pdf`, { type: "application/pdf" }); }
function downloadFile(file: File) { const url = URL.createObjectURL(file); const link = document.createElement("a"); link.href = url; link.download = file.name; link.click(); URL.revokeObjectURL(url); }
