import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { trpc } from "@/lib/trpc";
import { Settings2 } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Restricted } from "./AuditLog";

export default function SalesSettings() {
  const { user } = useAuth(); const isAdmin = user?.role === "admin"; const utils = trpc.useUtils(); const { data: settings } = trpc.commerce.settings.get.useQuery(undefined, { enabled: isAdmin }); const { data: agents = [] } = trpc.commerce.agents.list.useQuery(undefined, { enabled: isAdmin }); const [salesAgentId, setSalesAgentId] = useState("none"); const [cashierId, setCashierId] = useState("none"); const [requireSalesAgent, setRequireSalesAgent] = useState(false); const [requireCashier, setRequireCashier] = useState(false);
  useEffect(() => { if (settings) { setSalesAgentId(settings.defaultSalesAgentId ? String(settings.defaultSalesAgentId) : "none"); setCashierId(settings.defaultCashierId ? String(settings.defaultCashierId) : "none"); setRequireSalesAgent(settings.requireSalesAgent); setRequireCashier(settings.requireCashier); } }, [settings]);
  const save = trpc.commerce.settings.save.useMutation({ onSuccess: () => { utils.commerce.settings.get.invalidate(); toast.success("Paramètres de vente enregistrés."); } }); if (!isAdmin) return <Restricted title="Paramètres de vente" description="Seuls les administrateurs définissent les affectations par défaut des agents." />;
  const salesAgents = agents.filter(agent => agent.type === "sales_agent" && agent.active); const cashiers = agents.filter(agent => agent.type === "cashier" && agent.active);
  return <div className="mx-auto max-w-3xl space-y-6"><header><p className="text-xs font-medium uppercase tracking-[0.16em] text-cyan-300">Configuration</p><h1 className="mt-2 text-2xl font-semibold text-white sm:text-3xl">Paramètres de vente</h1></header><Card className="border-white/[0.07] bg-[#111722]"><CardContent className="space-y-6 p-6"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-400/10 text-cyan-300"><Settings2 className="h-5 w-5" /></span><p className="text-sm leading-6 text-slate-400">Le vendeur peut conserver ces agents par défaut ou choisir <strong className="font-medium text-slate-200">Aucun</strong> lorsque la règle n’est pas obligatoire.</p></div><SettingRow label="Agent commercial par défaut" description="Pré-rempli lors de la création d’une facture."><Select value={salesAgentId} onValueChange={setSalesAgentId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Aucun</SelectItem>{salesAgents.map(agent => <SelectItem key={agent.id} value={String(agent.id)}>{agent.name}</SelectItem>)}</SelectContent></Select></SettingRow><SettingRow label="Caissier par défaut" description="Pré-rempli lors de la création d’une facture."><Select value={cashierId} onValueChange={setCashierId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Aucun</SelectItem>{cashiers.map(agent => <SelectItem key={agent.id} value={String(agent.id)}>{agent.name}</SelectItem>)}</SelectContent></Select></SettingRow><ToggleRow label="Agent commercial obligatoire" description="La vente ne peut pas être facturée sans agent commercial." checked={requireSalesAgent} onCheckedChange={setRequireSalesAgent} /><ToggleRow label="Caissier obligatoire" description="La vente ne peut pas être facturée sans caissier." checked={requireCashier} onCheckedChange={setRequireCashier} /><Button onClick={() => save.mutate({ defaultSalesAgentId: salesAgentId === "none" ? null : Number(salesAgentId), defaultCashierId: cashierId === "none" ? null : Number(cashierId), requireSalesAgent, requireCashier, currency: settings?.currency ?? "XOF" }, { onError: error => toast.error(error.message) })} disabled={save.isPending} className="bg-cyan-400 text-slate-950">Enregistrer les paramètres</Button></CardContent></Card></div>;
}
function SettingRow({ label, description, children }: { label: string; description: string; children: React.ReactNode }) { return <div className="grid gap-3 border-t border-white/[0.07] pt-5 sm:grid-cols-[1fr_220px] sm:items-center"><div><Label className="text-sm text-slate-200">{label}</Label><p className="mt-1 text-xs text-slate-500">{description}</p></div>{children}</div>; }
function ToggleRow({ label, description, checked, onCheckedChange }: { label: string; description: string; checked: boolean; onCheckedChange: (value: boolean) => void }) { return <div className="flex items-center justify-between gap-4 border-t border-white/[0.07] pt-5"><div><Label className="text-sm text-slate-200">{label}</Label><p className="mt-1 text-xs text-slate-500">{description}</p></div><Switch checked={checked} onCheckedChange={onCheckedChange} /></div>; }
