import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { usePreferences, type Currency } from "@/contexts/PreferencesContext";
import { useTheme } from "@/contexts/ThemeContext";
import { trpc } from "@/lib/trpc";
import { Check, CircleDollarSign, Moon, Palette, Sun } from "lucide-react";
import { toast } from "sonner";
import { Restricted } from "./AuditLog";

const currencies: Array<{ code: Currency; name: string; symbol: string }> = [{ code: "XOF", name: "Franc CFA", symbol: "FCFA" }, { code: "USD", name: "Dollar américain", symbol: "$" }, { code: "EUR", name: "Euro", symbol: "€" }];
export default function Settings() {
  const { user } = useAuth(); const isAdmin = user?.role === "admin"; const { theme, setTheme } = useTheme(); const { currency, setCurrency } = usePreferences(); const utils = trpc.useUtils(); const { data } = trpc.commerce.settings.get.useQuery(undefined, { enabled: isAdmin });
  const save = trpc.commerce.settings.save.useMutation({ onSuccess: () => { utils.commerce.settings.get.invalidate(); toast.success("Préférences enregistrées."); }, onError: error => toast.error(error.message) });
  if (!isAdmin) return <Restricted title="Paramètres" description="La personnalisation de l’organisation est réservée aux administrateurs." />;
  const updateCurrency = (nextCurrency: Currency) => { setCurrency(nextCurrency); save.mutate({ defaultSalesAgentId: data?.defaultSalesAgentId ?? null, defaultCashierId: data?.defaultCashierId ?? null, requireSalesAgent: data?.requireSalesAgent ?? false, requireCashier: data?.requireCashier ?? false, currency: nextCurrency }); };
  return <div className="mx-auto max-w-5xl space-y-6"><header><p className="text-xs font-semibold uppercase tracking-[0.16em] text-cyan-300">Organisation</p><h1 className="mt-2 text-2xl font-semibold text-white sm:text-3xl">Paramètres</h1></header><section className="grid gap-6 lg:grid-cols-2"><Card className="border-white/[0.07] bg-[#111722]"><CardContent className="p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-400/10 text-cyan-300"><Palette className="h-5 w-5" /></span><div><h2 className="font-semibold text-white">Apparence</h2><p className="mt-1 text-sm text-slate-400">Choisissez l’espace de travail le plus adapté.</p></div></div><div className="mt-6 grid grid-cols-2 gap-3"><ThemeOption active={theme === "dark"} onClick={() => setTheme("dark")} icon={Moon} label="Sombre" detail="Cockpit nuit" preview="bg-[#0d1420]" /><ThemeOption active={theme === "light"} onClick={() => setTheme("light")} icon={Sun} label="Clair bleu" detail="Lisibilité renforcée" preview="bg-[#eaf4ff]" /></div></CardContent></Card><Card className="border-white/[0.07] bg-[#111722]"><CardContent className="p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-400/10 text-emerald-300"><CircleDollarSign className="h-5 w-5" /></span><div><h2 className="font-semibold text-white">Devise de référence</h2><p className="mt-1 text-sm text-slate-400">Utilisée pour les prix, ventes, marges et paie.</p></div></div><div className="mt-6 space-y-2">{currencies.map(item => <button key={item.code} onClick={() => updateCurrency(item.code)} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left transition ${currency === item.code ? "border-cyan-400/50 bg-cyan-400/10" : "border-white/10 hover:bg-white/[0.04]"}`}><span className="grid h-9 w-9 place-items-center rounded-lg bg-white/[0.07] text-sm font-bold text-cyan-300">{item.symbol}</span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-slate-100">{item.name}</span><span className="text-xs text-slate-500">{item.code}</span></span>{currency === item.code && <Check className="h-5 w-5 text-cyan-300" />}</button>)}</div><p className="mt-4 text-xs leading-5 text-slate-500">La devise choisie devient la référence de saisie et d’affichage. Aucun taux de conversion automatique n’est appliqué aux données existantes.</p></CardContent></Card></section></div>;
}
function ThemeOption({ active, onClick, icon: Icon, label, detail, preview }: { active: boolean; onClick: () => void; icon: typeof Moon; label: string; detail: string; preview: string }) { return <button onClick={onClick} className={`relative rounded-xl border p-3 text-left transition ${active ? "border-cyan-400/50 bg-cyan-400/10" : "border-white/10 hover:bg-white/[0.04]"}`}><span className={`mb-4 block h-14 rounded-lg ${preview} ring-1 ring-inset ring-white/10`} /><span className="flex items-center gap-2 text-sm font-semibold text-slate-100"><Icon className="h-4 w-4 text-cyan-300" />{label}</span><span className="mt-1 block text-xs text-slate-500">{detail}</span>{active && <span className="absolute right-3 top-3 grid h-5 w-5 place-items-center rounded-full bg-cyan-400 text-slate-950"><Check className="h-3.5 w-3.5" /></span>}</button>; }
