import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { displayCurrencyLabel, formatDate } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { ChevronLeft, History } from "lucide-react";
import { Link } from "wouter";
import { Restricted } from "./AuditLog";

export default function SettingsHistory() { const { user } = useAuth(); const isAdmin = user?.role === "admin"; const { data: logs = [], isLoading } = trpc.audit.list.useQuery(undefined, { enabled: isAdmin }); if (!isAdmin) return <Restricted title="Historique des paramètres" description="Cet historique est réservé aux administrateurs." />; const settingsLogs = logs.filter(log => log.entityType === "Entreprise" || log.entityType === "POS" || log.action.includes("Paramètres")); return <div className="mx-auto max-w-4xl space-y-6"><Link href="/parametres" className="inline-flex items-center gap-1 text-sm text-[#007B8B] hover:underline"><ChevronLeft className="h-4 w-4" />Retour aux paramètres</Link><header><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#007B8B]">Traçabilité</p><h1 className="mt-2 text-2xl font-semibold text-white sm:text-3xl">Historique des paramètres</h1></header><Card className="border-white/[0.07] bg-[#111722]"><CardContent className="p-0">{isLoading ? <p className="p-8 text-center text-sm text-slate-500">Chargement…</p> : settingsLogs.length ? <div className="divide-y divide-white/[0.07]">{settingsLogs.map(log => <div key={log.id} className="flex gap-4 p-5"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-[#007B8B]/10 text-[#00bcd4]"><History className="h-4 w-4" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Badge className="border-0 bg-white/[0.06] text-slate-300">{log.action}</Badge><span className="text-xs text-slate-500">{formatDate(log.createdAt, true)}</span></div><p className="mt-2 text-sm text-slate-300">{displayCurrencyLabel(log.detail || "Modification de paramètres")}</p><p className="mt-1 text-xs text-slate-500">Par {log.actorName || "Administrateur"}</p></div></div>)}</div> : <div className="p-12 text-center text-sm text-slate-500">Aucune modification de paramètres enregistrée.</div>}</CardContent></Card></div>; }
