import { useAuth } from "@/_core/hooks/useAuth";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Building2, ChevronRight, CircleDollarSign, DatabaseBackup, History, KeyRound, LayoutDashboard, Palette, ReceiptText, Search, Tags } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { Restricted } from "./AuditLog";

const links = [{ href: "/parametres/apparence", icon: Palette, label: "Apparence", detail: "Thème sombre ou clair bleu" }, { href: "/parametres/devise", icon: CircleDollarSign, label: "Devise", detail: "FCFA, USD ou EUR" }, { href: "/parametres/fiscalite", icon: Tags, label: "Fiscalité", detail: "TVA et taxes sur les documents" }, { href: "/parametres/identite", icon: Building2, label: "Identité & impression", detail: "Logo, signature et documents A4" }, { href: "/parametres/pos", icon: ReceiptText, label: "POS & ticket", detail: "Affectations de vente et impression ticket" }, { href: "/parametres/tableau-de-bord", icon: LayoutDashboard, label: "Tableau de bord", detail: "Éléments visibles dans le cockpit" }, { href: "/parametres/securite", icon: KeyRound, label: "Sécurité du compte", detail: "Sessions actives et mot de passe administrateur" }, { href: "/parametres/historique", icon: History, label: "Historique", detail: "Modifications des paramètres" }, { href: "/sauvegardes", icon: DatabaseBackup, label: "Sauvegardes", detail: "Archives locales, restauration et Google Drive" }];

export default function SettingsIndex() {
  const { user } = useAuth();
  const [query, setQuery] = useState("");
  const filteredLinks = useMemo(() => { const normalized = query.trim().toLocaleLowerCase(); if (!normalized) return links; return links.filter(item => `${item.label} ${item.detail}`.toLocaleLowerCase().includes(normalized)); }, [query]);
  if (user?.role !== "admin") return <Restricted title="Paramètres" description="La personnalisation de l’organisation est réservée aux administrateurs." />;
  return <div className="mx-auto max-w-4xl space-y-6"><header><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#007B8B]">Organisation</p><h1 className="mt-2 text-2xl font-semibold text-white sm:text-3xl">Paramètres</h1><p className="mt-2 text-sm text-slate-400">Recherchez rapidement un réglage par nom ou par fonctionnalité.</p></header><div className="relative"><Search className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-slate-500" /><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Rechercher un paramètre…" aria-label="Rechercher un paramètre" className="border-white/[0.12] bg-[#111722] pl-9 text-white placeholder:text-slate-500" /></div><Card className="border-white/[0.07] bg-[#111722]"><CardContent className="p-3">{filteredLinks.length ? filteredLinks.map(item => <Link key={item.href} href={item.href} className="group flex items-center gap-4 rounded-xl px-4 py-4 transition hover:bg-white/[0.05]"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#007B8B]/10 text-[#00bcd4]"><item.icon className="h-5 w-5" /></span><span className="min-w-0 flex-1"><span className="block font-semibold text-slate-100">{item.label}</span><span className="mt-1 block text-sm text-slate-500">{item.detail}</span></span><ChevronRight className="h-5 w-5 text-slate-500 transition group-hover:translate-x-0.5 group-hover:text-[#00bcd4]" /></Link>) : <p className="px-4 py-10 text-center text-sm text-slate-400">Aucun paramètre ne correspond à « {query} ».</p>}</CardContent></Card></div>;
}
