import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { trpc } from "@/lib/trpc";
import { Link } from "wouter";
import { ChevronLeft, ReceiptText, Settings2 } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Restricted } from "./AuditLog";

export default function SettingsPos() {
  const { user } = useAuth(); const isAdmin = user?.role === "admin"; const utils = trpc.useUtils(); const { data: settings } = trpc.commerce.settings.get.useQuery(undefined, { enabled: isAdmin }); const { data: agents = [] } = trpc.commerce.agents.list.useQuery(undefined, { enabled: isAdmin });
  const [salesAgentId, setSalesAgentId] = useState("none"); const [cashierId, setCashierId] = useState("none"); const [requireSalesAgent, setRequireSalesAgent] = useState(false); const [requireCashier, setRequireCashier] = useState(false); const [ticketHeader, setTicketHeader] = useState("Merci de votre achat"); const [ticketFooter, setTicketFooter] = useState("À bientôt"); const [ticketWidthMm, setTicketWidthMm] = useState<"58" | "80">("80");
  useEffect(() => { if (settings) { setSalesAgentId(settings.defaultSalesAgentId ? String(settings.defaultSalesAgentId) : "none"); setCashierId(settings.defaultCashierId ? String(settings.defaultCashierId) : "none"); setRequireSalesAgent(settings.requireSalesAgent); setRequireCashier(settings.requireCashier); setTicketHeader(settings.ticketHeader || "Merci de votre achat"); setTicketFooter(settings.ticketFooter || "À bientôt"); setTicketWidthMm(settings.ticketWidthMm || "80"); } }, [settings]);
  const save = trpc.commerce.settings.save.useMutation({ onSuccess: () => { utils.commerce.settings.get.invalidate(); toast.success("Réglages POS et ticket enregistrés."); }, onError: error => toast.error(error.message) });
  if (!isAdmin) return <Restricted title="POS & ticket" description="Les réglages du point de vente sont réservés aux administrateurs." />;
  const salesAgents = agents.filter(agent => agent.type === "sales_agent" && agent.active); const cashiers = agents.filter(agent => agent.type === "cashier" && agent.active);
  const saveSettings = () => save.mutate({ defaultSalesAgentId: salesAgentId === "none" ? null : Number(salesAgentId), defaultCashierId: cashierId === "none" ? null : Number(cashierId), requireSalesAgent, requireCashier, currency: settings?.currency ?? "XOF", ticketHeader, ticketFooter, ticketWidthMm });
  return <div className="mx-auto max-w-4xl space-y-6"><Link href="/parametres" className="inline-flex items-center gap-1 text-sm text-[#007B8B] hover:underline"><ChevronLeft className="h-4 w-4" />Retour aux paramètres</Link><header><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#007B8B]">Point de vente</p><h1 className="mt-2 text-2xl font-semibold text-white sm:text-3xl">POS & impression ticket</h1></header><div className="grid gap-6 lg:grid-cols-2"><Card className="border-white/[0.07] bg-[#111722]"><CardContent className="space-y-5 p-6"><div className="flex items-center gap-3"><Settings2 className="h-5 w-5 text-[#00bcd4]" /><h2 className="font-semibold text-slate-100">Affectations POS</h2></div><Row label="Agent commercial par défaut"><Select value={salesAgentId} onValueChange={setSalesAgentId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Aucun</SelectItem>{salesAgents.map(agent => <SelectItem key={agent.id} value={String(agent.id)}>{agent.name}</SelectItem>)}</SelectContent></Select></Row><Row label="Caissier par défaut"><Select value={cashierId} onValueChange={setCashierId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Aucun</SelectItem>{cashiers.map(agent => <SelectItem key={agent.id} value={String(agent.id)}>{agent.name}</SelectItem>)}</SelectContent></Select></Row><Toggle label="Agent commercial obligatoire" checked={requireSalesAgent} onChange={setRequireSalesAgent} /><Toggle label="Caissier obligatoire" checked={requireCashier} onChange={setRequireCashier} /></CardContent></Card><Card className="border-white/[0.07] bg-[#111722]"><CardContent className="space-y-5 p-6"><div className="flex items-center gap-3"><ReceiptText className="h-5 w-5 text-[#00bcd4]" /><h2 className="font-semibold text-slate-100">Ticket de caisse</h2></div><Row label="Largeur"><Select value={ticketWidthMm} onValueChange={value => setTicketWidthMm(value as "58" | "80")}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="58">58 mm</SelectItem><SelectItem value="80">80 mm</SelectItem></SelectContent></Select></Row><Field label="En-tête du ticket"><Input value={ticketHeader} onChange={event => setTicketHeader(event.target.value)} maxLength={160} /></Field><Field label="Pied du ticket"><Input value={ticketFooter} onChange={event => setTicketFooter(event.target.value)} maxLength={240} /></Field></CardContent></Card></div><Button onClick={saveSettings} disabled={save.isPending} className="bg-[#007B8B] text-white hover:bg-[#006a78]">{save.isPending ? "Enregistrement…" : "Enregistrer les réglages POS"}</Button></div>;
}
function Row({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label className="text-sm text-slate-200">{label}</Label>{children}</div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label className="text-sm text-slate-200">{label}</Label>{children}</div>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <div className="flex items-center justify-between gap-4 border-t border-white/[0.07] pt-4"><Label className="text-sm text-slate-200">{label}</Label><Switch checked={checked} onCheckedChange={onChange} /></div>; }
