import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { formatCurrency, formatDate, formatSignedQuantity } from "@/lib/format";
import { recommendedRestockQuantity, restockEstimateCents } from "@/lib/replenishmentRules";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Building2, CalendarDays, CheckCircle2, Edit3, Mail, MapPin, MessageCircle, PackageCheck, Phone, Printer, Send, ShoppingCart, Trash2, Truck, WalletCards } from "lucide-react";
import { jsPDF } from "jspdf";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { toast } from "sonner";
import { useLocation, useRoute } from "wouter";

type SupplierForm = { name: string; address: string; email: string; phone: string; taxNumber: string; notes: string };
type OrderStatus = "draft" | "sent" | "received" | "cancelled";
type OrderItem = { id: number; productName: string; productReference: string; unit: string; quantity: number; receivedQuantity: number; purchasePriceCents: number; lineTotalCents: number };
type PurchaseOrder = { id: number; orderNumber: string; status: OrderStatus; totalCents: number; notes: string | null; cancellationReason: string | null; expectedDeliveryDate: Date | null; createdAt: Date; items: OrderItem[] };

const statusMeta: Record<OrderStatus, { label: string; className: string }> = {
  draft: { label: "En attente", className: "border-amber-400/25 bg-amber-400/10 text-amber-200" },
  sent: { label: "Envoyé", className: "border-sky-400/25 bg-sky-400/10 text-sky-200" },
  received: { label: "Reçu", className: "border-emerald-400/25 bg-emerald-400/10 text-emerald-200" },
  cancelled: { label: "Annulé", className: "border-rose-400/25 bg-rose-400/10 text-rose-200" },
};

export default function SupplierDetail() {
  const [, params] = useRoute("/fournisseurs/:id");
  const [, setLocation] = useLocation();
  const supplierId = Number(params?.id);
  const { user } = useAuth();
  const canManage = user?.role === "admin";
  const utils = trpc.useUtils();
  const { data: suppliers = [], isLoading } = trpc.suppliers.list.useQuery();
  const { data: products = [] } = trpc.products.list.useQuery();
  const { data: movements = [] } = trpc.movements.list.useQuery();
  const { data: orders = [] } = trpc.purchaseOrders.listBySupplier.useQuery({ supplierId }, { enabled: Number.isInteger(supplierId) && supplierId > 0 });
  const supplier = suppliers.find(value => value.id === supplierId);
  const [editOpen, setEditOpen] = useState(false);
  const [receiptOrder, setReceiptOrder] = useState<PurchaseOrder | null>(null);
  const [cancelOrder, setCancelOrder] = useState<PurchaseOrder | null>(null);
  const [quantities, setQuantities] = useState<Record<number, number>>({});
  const [notes, setNotes] = useState("");
  const [expectedDeliveryDate, setExpectedDeliveryDate] = useState("");
  const linkedProducts = useMemo(() => products.filter(product => product.supplierId === supplierId), [products, supplierId]);
  const entries = useMemo(() => movements.filter(movement => movement.supplierId === supplierId && movement.type === "entry"), [movements, supplierId]);
  const selectedLines = linkedProducts.filter(product => quantities[product.id] > 0).map(product => ({ productId: product.id, quantity: quantities[product.id] }));
  const refreshOrderData = async () => { await Promise.all([utils.purchaseOrders.listBySupplier.invalidate({ supplierId }), utils.movements.list.invalidate(), utils.products.list.invalidate()]); };
  const createOrder = trpc.purchaseOrders.create.useMutation({ onSuccess: async result => { await refreshOrderData(); toast.success(`Bon de commande ${result.orderNumber} créé.`); if (supplier) printOrder(supplier, result.orderNumber, linkedProducts.filter(product => quantities[product.id] > 0).map(product => ({ ...product, orderQuantity: quantities[product.id] }))); setQuantities({}); setNotes(""); setExpectedDeliveryDate(""); }, onError: error => toast.error(error.message) });
  const markSent = trpc.purchaseOrders.markSent.useMutation({ onError: error => toast.error(error.message) });
  const receiveOrder = trpc.purchaseOrders.receive.useMutation({ onSuccess: async result => { await refreshOrderData(); setReceiptOrder(null); toast.success(result.alreadyReceived ? "Ce bon avait déjà été réceptionné." : ("complete" in result && result.complete ? "Réception complète : le stock a été mis à jour." : "Réception partielle enregistrée : le reliquat reste à recevoir.")); }, onError: error => toast.error(error.message) });
  const cancelPurchaseOrder = trpc.purchaseOrders.cancel.useMutation({ onSuccess: async () => { await refreshOrderData(); setCancelOrder(null); toast.success("Bon de commande annulé avec son motif."); }, onError: error => toast.error(error.message) });
  const removeSupplier = trpc.suppliers.remove.useMutation({ onSuccess: async () => { await utils.suppliers.list.invalidate(); toast.success("Fournisseur supprimé."); setLocation("/fournisseurs"); }, onError: error => toast.error(error.message) });

  if (isLoading) return <div className="mx-auto max-w-[1500px] py-24 text-center text-sm text-slate-500">Chargement du fournisseur…</div>;
  if (!supplier) return <MissingSupplier onBack={() => setLocation("/fournisseurs")} />;
  const phoneDigits = (supplier.phone || "").replace(/[^\d]/g, "");
  const setQuantity = (productId: number, next: number) => setQuantities(current => ({ ...current, [productId]: Math.max(0, Math.floor(next) || 0) }));
  const startOrder = () => { if (!selectedLines.length) return toast.error("Sélectionnez au moins un produit à commander."); createOrder.mutate({ supplierId, notes: notes.trim() || null, expectedDeliveryDate: expectedDeliveryDate ? new Date(`${expectedDeliveryDate}T12:00:00`) : null, items: selectedLines }); };
  const shareOrder = async (order: PurchaseOrder, channel: "whatsapp" | "email") => {
    const message = buildShareMessage(supplier.name, order);
    if (channel === "email") {
      if (!supplier.email) return toast.error("L’adresse e-mail du fournisseur est indisponible.");
      const file = createOrderPdf(supplier, order);
      if (navigator.canShare?.({ files: [file] })) {
        try { await navigator.share({ title: `Bon de commande ${order.orderNumber}`, text: message, files: [file] }); } catch { return; }
      } else {
        downloadOrderPdf(file);
        window.location.href = `mailto:${supplier.email}?subject=${encodeURIComponent(`Bon de commande ${order.orderNumber}`)}&body=${encodeURIComponent(`${message}\n\nLe PDF du bon a été téléchargé : joignez-le à ce message.`)}`;
        toast.info("Le PDF a été téléchargé. Joignez-le au message e-mail qui s’ouvre.");
      }
      markSent.mutate({ id: order.id }, { onSuccess: refreshOrderData });
      return;
    }
    if (!phoneDigits) return toast.error("Le numéro WhatsApp du fournisseur est indisponible.");
    const shareWindow = window.open("", "_blank");
    markSent.mutate({ id: order.id }, { onSuccess: async () => { await refreshOrderData(); const url = `https://wa.me/${phoneDigits}?text=${encodeURIComponent(message)}`; if (shareWindow) shareWindow.location.href = url; else window.location.assign(url); }});
  };

  return <div className="mx-auto max-w-[1500px] space-y-6">
    <Button variant="ghost" onClick={() => setLocation("/fournisseurs")} className="-ml-3 text-primary hover:text-primary"><ArrowLeft className="mr-2 h-4 w-4" />Retour aux fournisseurs</Button>
    <section className="rounded-2xl border border-white/[0.07] bg-[#111722] p-5 shadow-sm sm:p-6">
      <div className="flex min-w-0 items-start gap-4">
        <span className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-primary/10 text-primary"><Building2 className="h-7 w-7" /></span>
        <div className="min-w-0 flex-1">
          <p className="text-xs font-medium uppercase tracking-[0.16em] text-primary">Fournisseur</p>
          <div className="mt-1 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
            <div className="min-w-0"><h1 className="truncate text-2xl font-semibold tracking-tight text-white sm:text-3xl">{supplier.name}</h1><p className="mt-2 text-sm text-slate-400">{supplier.address || "Adresse non renseignée"}</p></div>
            {canManage && <div className="flex shrink-0 flex-wrap gap-2"><Button onClick={() => setEditOpen(true)} className="bg-primary text-primary-foreground hover:bg-primary/90"><Edit3 className="mr-2 h-4 w-4" />Modifier</Button><Button variant="outline" onClick={() => { if (window.confirm(`Supprimer ${supplier.name} ?`)) removeSupplier.mutate({ id: supplier.id }); }} disabled={removeSupplier.isPending} className="border-rose-400/30 text-rose-300 hover:bg-rose-400/10 hover:text-rose-200"><Trash2 className="mr-2 h-4 w-4" />Supprimer</Button></div>}
          </div>
        </div>
      </div>
      <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Info label="Téléphone" value={supplier.phone || "Non renseigné"} icon={<Phone className="h-4 w-4" />} /><Info label="E-mail" value={supplier.email || "Non renseigné"} icon={<Mail className="h-4 w-4" />} /><Info label="Numéro fiscal" value={supplier.taxNumber || "Non renseigné"} icon={<WalletCards className="h-4 w-4" />} /><Info label="Produits rattachés" value={`${linkedProducts.length} référence${linkedProducts.length > 1 ? "s" : ""}`} icon={<PackageCheck className="h-4 w-4" />} /></div>
      <div className="mt-5 flex flex-wrap gap-2 border-t border-white/[0.07] pt-5"><ContactButton label="Appeler" icon={<Phone className="h-4 w-4" />} href={supplier.phone ? `tel:${supplier.phone}` : undefined} /><ContactButton label="Message" icon={<MessageCircle className="h-4 w-4" />} href={phoneDigits ? `sms:${phoneDigits}` : undefined} /><ContactButton label="Mail" icon={<Mail className="h-4 w-4" />} href={supplier.email ? `mailto:${supplier.email}` : undefined} /></div>
    </section>
    <SupplierNotes notes={supplier.notes} />
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(340px,.8fr)]"><section className="space-y-6"><Card className="border-white/[0.07] bg-[#111722] shadow-none"><CardContent className="p-5 sm:p-6"><div className="flex items-center gap-2"><ShoppingCart className="h-5 w-5 text-primary" /><h2 className="text-lg font-semibold text-white">Préparer un bon de commande</h2></div>{linkedProducts.length ? <><div className="mt-5 space-y-2">{linkedProducts.map(product => { const selected = quantities[product.id] > 0; const suggested = recommendedRestockQuantity(product.minimumQuantity, product.quantity); return <div key={product.id} className={`flex flex-col gap-3 rounded-xl border p-3 transition sm:flex-row sm:items-center ${selected ? "border-primary/40 bg-primary/[0.06]" : "border-white/[0.07] bg-white/[0.02]"}`}><Checkbox checked={selected} onCheckedChange={checked => setQuantity(product.id, checked ? (quantities[product.id] || suggested) : 0)} aria-label={`Sélectionner ${product.name}`} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-100">{product.name}</p><p className="mt-0.5 text-xs text-slate-500">{product.reference} · Stock {product.quantity} {product.unit} · Achat {formatCurrency(product.purchasePriceCents)}</p></div><div className="flex items-center justify-between gap-2 sm:justify-end"><Label className="text-xs text-slate-500">Qté</Label><Input type="number" min="1" value={quantities[product.id] || ""} placeholder={String(suggested)} onChange={event => setQuantity(product.id, Number(event.target.value))} className="h-9 w-20 border-white/10 bg-[#0e141f] text-right" /></div></div>; })}</div><div className="mt-5 grid gap-3 sm:grid-cols-[1fr_auto]"><Textarea value={notes} onChange={event => setNotes(event.target.value)} placeholder="Note à afficher sur le bon de commande" className="min-h-10 border-white/10 bg-[#0e141f]" /><Button onClick={startOrder} disabled={createOrder.isPending || !selectedLines.length} className="h-auto bg-primary text-primary-foreground hover:bg-primary/90"><Printer className="mr-2 h-4 w-4" />{createOrder.isPending ? "Création…" : "Créer et imprimer"}</Button></div><div className="mt-3 flex items-center justify-between text-sm"><span className="text-slate-500">{selectedLines.length} produit{selectedLines.length > 1 ? "s" : ""} sélectionné{selectedLines.length > 1 ? "s" : ""}</span><span className="font-semibold text-slate-100">{formatCurrency(linkedProducts.filter(product => quantities[product.id] > 0).reduce((sum, product) => sum + restockEstimateCents(quantities[product.id], product.purchasePriceCents), 0))}</span></div></> : <Empty icon={<Truck className="h-5 w-5" />} text="Aucun produit n’est encore rattaché à ce fournisseur." />}</CardContent></Card>
      <History title="Historique des commandes" icon={<CalendarDays className="h-5 w-5 text-primary" />}>{orders.length ? <div className="grid gap-3">{(orders as PurchaseOrder[]).map(order => <SupplierOrderCard key={order.id} order={order} onOpen={() => setLocation(`/bons-commande/${order.id}`)} />)}</div> : <Empty icon={<ShoppingCart className="h-5 w-5" />} text="Aucun bon de commande enregistré." />}</History></section>
      <aside className="space-y-6"><History title="Historique des approvisionnements" icon={<Truck className="h-5 w-5 text-primary" />}>{entries.length ? <div className="divide-y divide-white/[0.07] overflow-hidden rounded-xl border border-white/[0.07]">{entries.slice(0, 12).map(entry => <div key={entry.id} className="flex items-center justify-between gap-3 px-4 py-3"><div className="min-w-0"><p className="truncate text-sm font-medium text-slate-200">{entry.productName}</p><p className="mt-0.5 text-xs text-slate-500">{formatDate(entry.occurredAt)} · {entry.reason}</p></div><span className="shrink-0 text-sm font-semibold text-emerald-300">{formatSignedQuantity(entry.quantity)}</span></div>)}</div> : <Empty icon={<PackageCheck className="h-5 w-5" />} text="Aucun approvisionnement lié à ce fournisseur." />}</History></aside></div>
    <SupplierEditDialog supplier={supplier} open={editOpen} onOpenChange={setEditOpen} />
    <ReceiptOrderDialog order={receiptOrder} pending={receiveOrder.isPending} onOpenChange={open => !open && setReceiptOrder(null)} onConfirm={lines => receiptOrder && receiveOrder.mutate({ id: receiptOrder.id, lines })} />
    <CancelOrderDialog order={cancelOrder} pending={cancelPurchaseOrder.isPending} onOpenChange={open => !open && setCancelOrder(null)} onConfirm={reason => cancelOrder && cancelPurchaseOrder.mutate({ id: cancelOrder.id, reason })} />
  </div>;
}

function OrderRow({ order, canManage, canWhatsapp, canEmail, sending, receiving, onWhatsapp, onEmail, onReceive, onCancel }: { order: PurchaseOrder; canManage: boolean; canWhatsapp: boolean; canEmail: boolean; sending: boolean; receiving: boolean; onWhatsapp: () => void; onEmail: () => void; onReceive: () => void; onCancel: () => void }) { const received = order.items.reduce((sum, item) => sum + item.receivedQuantity, 0); const ordered = order.items.reduce((sum, item) => sum + item.quantity, 0); const actionable = order.status !== "received" && order.status !== "cancelled"; return <div className="px-4 py-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-slate-100">{order.orderNumber}</p><StatusBadge status={order.status} /></div><p className="mt-1 text-xs text-slate-500">{formatDate(order.createdAt)} · {order.items.length} produit{order.items.length > 1 ? "s" : ""} · {formatCurrency(order.totalCents)}</p>{received > 0 && <p className="mt-1 text-xs font-medium text-emerald-300">{received} / {ordered} unité{ordered > 1 ? "s" : ""} réceptionnée{received > 1 ? "s" : ""}</p>}{order.notes && <p className="mt-2 text-xs text-slate-400">{order.notes}</p>}{order.cancellationReason && <p className="mt-2 text-xs text-rose-300">Motif d’annulation : {order.cancellationReason}</p>}</div>{canManage && <div className="flex flex-wrap gap-2 sm:justify-end"><Button size="sm" variant="outline" disabled={!canWhatsapp || sending || order.status === "cancelled"} onClick={onWhatsapp} className="border-white/10 text-slate-300 hover:bg-primary/[0.06] hover:text-primary"><MessageCircle className="mr-1.5 h-3.5 w-3.5" />WhatsApp</Button><Button size="sm" variant="outline" disabled={!canEmail || sending || order.status === "cancelled"} onClick={onEmail} className="border-white/10 text-slate-300 hover:bg-primary/[0.06] hover:text-primary"><Send className="mr-1.5 h-3.5 w-3.5" />E-mail + PDF</Button>{actionable && <><Button size="sm" disabled={receiving} onClick={onReceive} className="bg-primary text-primary-foreground hover:bg-primary/90"><CheckCircle2 className="mr-1.5 h-3.5 w-3.5" />Réceptionner</Button><Button size="sm" variant="outline" onClick={onCancel} className="border-rose-400/30 text-rose-300 hover:bg-rose-400/10"><Trash2 className="mr-1.5 h-3.5 w-3.5" />Annuler</Button></>}</div>}</div></div>; }
function SupplierOrderCard({ order, onOpen }: { order: PurchaseOrder; onOpen: () => void }) { const received = order.items.reduce((sum, item) => sum + item.receivedQuantity, 0); const expected = order.expectedDeliveryDate ? new Date(order.expectedDeliveryDate) : null; const today = new Date(); today.setHours(0, 0, 0, 0); const overdue = Boolean(expected && expected < today && order.status !== "received" && order.status !== "cancelled"); return <button type="button" onClick={onOpen} className={`w-full rounded-xl border p-4 text-left transition hover:-translate-y-0.5 hover:border-primary/45 hover:bg-primary/[0.05] ${overdue ? "border-rose-400/35 bg-rose-400/[0.04]" : "border-white/[0.07] bg-white/[0.02]"}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="font-semibold text-slate-100">{order.orderNumber}</span><StatusBadge status={order.status} /></div><p className="mt-1 text-xs text-slate-500">Commandé le {formatDate(order.createdAt)} · {order.items.length} produit{order.items.length > 1 ? "s" : ""}</p></div><span className="shrink-0 text-sm font-semibold text-slate-100">{formatCurrency(order.totalCents)}</span></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-xs"><span className={overdue ? "font-medium text-rose-300" : "text-slate-400"}>{expected ? `${overdue ? "En retard · " : "Livraison prévue · "}${formatDate(expected)}` : "Livraison non planifiée"}</span>{received > 0 && <span className="text-emerald-300">{received} unité{received > 1 ? "s" : ""} reçue{received > 1 ? "s" : ""}</span>}</div></button>; }
function ReceiptOrderDialog({ order, pending, onOpenChange, onConfirm }: { order: PurchaseOrder | null; pending: boolean; onOpenChange: (open: boolean) => void; onConfirm: (lines: Array<{ id: number; quantity: number }>) => void }) { const [quantities, setQuantities] = useState<Record<number, number>>({}); useEffect(() => { if (order) setQuantities(Object.fromEntries(order.items.map(item => [item.id, item.quantity - item.receivedQuantity]))); }, [order]); if (!order) return null; const lines = order.items.map(item => ({ id: item.id, quantity: Math.max(0, Math.min(item.quantity - item.receivedQuantity, quantities[item.id] ?? 0)) })).filter(item => item.quantity > 0); return <Dialog open={Boolean(order)} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto border-white/10 bg-[#141b27] text-slate-100 sm:max-w-2xl"><DialogHeader><DialogTitle>Réception partielle · {order.orderNumber}</DialogTitle></DialogHeader><div className="space-y-3 py-2">{order.items.map(item => { const remaining = item.quantity - item.receivedQuantity; return <div key={item.id} className="grid gap-2 rounded-xl border border-white/[0.07] bg-white/[0.025] p-3 sm:grid-cols-[1fr_auto]"><div><p className="text-sm font-semibold text-slate-100">{item.productName}</p><p className="mt-1 text-xs text-slate-500">Commandé : {item.quantity} {item.unit} · Déjà reçu : {item.receivedQuantity} · Reste : {remaining}</p></div><Input type="number" min="0" max={remaining} disabled={remaining === 0} value={quantities[item.id] ?? 0} onChange={event => setQuantities(current => ({ ...current, [item.id]: Number(event.target.value) || 0 }))} className="h-9 w-full border-white/10 bg-[#0e141f] text-right sm:w-24" /></div>; })}</div><DialogFooter><Button variant="ghost" onClick={() => onOpenChange(false)}>Annuler</Button><Button onClick={() => onConfirm(lines)} disabled={!lines.length || pending} className="bg-primary text-primary-foreground hover:bg-primary/90"><CheckCircle2 className="mr-2 h-4 w-4" />{pending ? "Validation…" : "Valider la réception"}</Button></DialogFooter></DialogContent></Dialog>; }
function CancelOrderDialog({ order, pending, onOpenChange, onConfirm }: { order: PurchaseOrder | null; pending: boolean; onOpenChange: (open: boolean) => void; onConfirm: (reason: string) => void }) { const [reason, setReason] = useState(""); useEffect(() => { if (order) setReason(""); }, [order]); if (!order) return null; return <Dialog open={Boolean(order)} onOpenChange={onOpenChange}><DialogContent className="border-white/10 bg-[#141b27] text-slate-100"><DialogHeader><DialogTitle>Annuler le bon {order.orderNumber}</DialogTitle></DialogHeader><div className="py-2"><Label className="text-xs font-medium text-slate-300">Motif d’annulation *</Label><Textarea value={reason} onChange={event => setReason(event.target.value)} placeholder="Expliquez la raison de l’annulation" className="mt-2 min-h-28 border-white/10 bg-[#0e141f]" /></div><DialogFooter><Button variant="ghost" onClick={() => onOpenChange(false)}>Retour</Button><Button disabled={pending || reason.trim().length < 3} onClick={() => onConfirm(reason.trim())} className="bg-rose-600 text-white hover:bg-rose-500"><Trash2 className="mr-2 h-4 w-4" />{pending ? "Annulation…" : "Confirmer l’annulation"}</Button></DialogFooter></DialogContent></Dialog>; }
function StatusBadge({ status }: { status: OrderStatus }) { const meta = statusMeta[status]; return <span className={`rounded-full border px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.08em] ${meta.className}`}>{meta.label}</span>; }
function SupplierEditDialog({ supplier, open, onOpenChange }: { supplier: any; open: boolean; onOpenChange: (value: boolean) => void }) { const utils = trpc.useUtils(); const [form, setForm] = useState<SupplierForm>({ name: supplier.name, address: supplier.address || "", email: supplier.email || "", phone: supplier.phone || "", taxNumber: supplier.taxNumber || "", notes: supplier.notes || "" }); const update = trpc.suppliers.update.useMutation({ onSuccess: async () => { await utils.suppliers.list.invalidate(); toast.success("Fournisseur mis à jour."); onOpenChange(false); }, onError: error => toast.error(error.message) }); const submit = () => { if (!form.name.trim()) return toast.error("Le nom du fournisseur est requis."); update.mutate({ id: supplier.id, name: form.name.trim(), otherReference: null, address: form.address.trim() || null, email: form.email.trim() || null, phone: form.phone.trim() || null, taxNumber: form.taxNumber.trim() || null, notes: form.notes.trim() || null }); }; return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto border-white/10 bg-[#141b27] text-slate-100"><DialogHeader><DialogTitle>Modifier le fournisseur</DialogTitle></DialogHeader><div className="grid gap-4 py-2"><Field label="Nom *"><Input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} /></Field><Field label="Adresse"><Input value={form.address} onChange={event => setForm({ ...form, address: event.target.value })} /></Field><Field label="Email"><Input type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} /></Field><Field label="Téléphone"><Input value={form.phone} onChange={event => setForm({ ...form, phone: event.target.value })} /></Field><Field label="Numéro fiscal"><Input value={form.taxNumber} onChange={event => setForm({ ...form, taxNumber: event.target.value })} /></Field><Field label="Notes"><Textarea value={form.notes} onChange={event => setForm({ ...form, notes: event.target.value })} /></Field></div><DialogFooter><Button variant="ghost" onClick={() => onOpenChange(false)}>Annuler</Button><Button onClick={submit} disabled={update.isPending} className="bg-primary text-primary-foreground hover:bg-primary/90">Enregistrer</Button></DialogFooter></DialogContent></Dialog>; }
function MissingSupplier({ onBack }: { onBack: () => void }) { return <div className="mx-auto max-w-[1500px] space-y-5"><Button variant="ghost" onClick={onBack} className="text-primary"><ArrowLeft className="mr-2 h-4 w-4" />Retour aux fournisseurs</Button><Card className="border-dashed border-white/10 bg-[#111722] shadow-none"><CardContent className="py-16 text-center"><Building2 className="mx-auto h-7 w-7 text-slate-600" /><p className="mt-4 font-medium text-slate-300">Fournisseur introuvable</p></CardContent></Card></div>; }
function ContactButton({ label, icon, href, external = false }: { label: string; icon: ReactNode; href?: string; external?: boolean }) { return <Button variant="outline" disabled={!href} asChild={Boolean(href)} className="border-white/10 text-slate-300 hover:border-primary/40 hover:bg-primary/[0.06] hover:text-primary disabled:opacity-45">{href ? <a href={href} target={external ? "_blank" : undefined} rel={external ? "noreferrer" : undefined}>{icon}<span className="ml-2">{label}</span></a> : <span>{icon}<span className="ml-2">{label}</span></span>}</Button>; }
function Info({ label, value, icon }: { label: string; value: string; icon: ReactNode }) { return <div className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-3"><p className="flex items-center gap-2 text-[10px] font-medium uppercase tracking-[0.11em] text-slate-500">{icon}{label}</p><p className="mt-1 truncate text-sm font-medium text-slate-200">{value}</p></div>; }
function SupplierNotes({ notes }: { notes: string | null }) { return <Card className="border-white/[0.07] bg-[#111722] shadow-none"><CardContent className="p-5 sm:p-6"><div className="flex items-center gap-2"><MapPin className="h-5 w-5 text-primary" /><h2 className="text-base font-semibold text-white">Informations complémentaires</h2></div><p className="mt-4 whitespace-pre-line text-sm leading-relaxed text-slate-400">{notes || "Aucune note enregistrée."}</p></CardContent></Card>; }
function History({ title, icon, children }: { title: string; icon: ReactNode; children: ReactNode }) { return <Card className="border-white/[0.07] bg-[#111722] shadow-none"><CardContent className="p-5 sm:p-6"><div className="flex items-center gap-2">{icon}<h2 className="text-lg font-semibold text-white">{title}</h2></div><div className="mt-5">{children}</div></CardContent></Card>; }
function Empty({ icon, text }: { icon: ReactNode; text: string }) { return <div className="rounded-xl border border-dashed border-white/10 px-4 py-8 text-center"><span className="mx-auto grid h-9 w-9 place-items-center rounded-xl bg-white/[0.035] text-slate-500">{icon}</span><p className="mt-3 text-sm text-slate-500">{text}</p></div>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <div className="space-y-2"><Label className="text-xs font-medium text-slate-300">{label}</Label>{children}</div>; }
function buildShareMessage(supplierName: string, order: PurchaseOrder) { return [`Bonjour ${supplierName},`, "", `Veuillez trouver notre bon de commande ${order.orderNumber}.`, "", ...order.items.map(item => `• ${item.productName} (${item.productReference}) — ${item.quantity} ${item.unit}`), "", `Total : ${formatCurrency(order.totalCents)}`, order.notes ? `Note : ${order.notes}` : "", "", "Merci."].filter(Boolean).join("\n"); }
function createOrderPdf(supplier: { name: string; address: string | null }, order: PurchaseOrder) { const doc = new jsPDF({ unit: "pt", format: "a4" }); let y = 56; doc.setFontSize(20); doc.setTextColor(0, 123, 139); doc.text("Bon de commande", 44, y); y += 24; doc.setFontSize(10); doc.setTextColor(90, 101, 115); doc.text(`${order.orderNumber} · ${formatDate(order.createdAt)}`, 44, y); doc.text(supplier.name, 420, 56, { align: "right" }); if (supplier.address) doc.text(supplier.address, 420, 72, { align: "right" }); y += 38; doc.setDrawColor(0, 123, 139); doc.line(44, y, 552, y); y += 24; doc.setFontSize(9); doc.setTextColor(30, 41, 59); doc.text("Produit", 44, y); doc.text("Référence", 250, y); doc.text("Qté", 380, y); doc.text("Total", 552, y, { align: "right" }); y += 14; doc.setDrawColor(220, 229, 237); order.items.forEach(item => { if (y > 760) { doc.addPage(); y = 56; } doc.line(44, y, 552, y); y += 16; doc.text(item.productName, 44, y); doc.text(item.productReference, 250, y); doc.text(`${item.quantity} ${item.unit}`, 380, y); doc.text(formatCurrency(item.lineTotalCents), 552, y, { align: "right" }); y += 12; }); y += 20; doc.setFontSize(12); doc.setTextColor(15, 23, 42); doc.text(`Total : ${formatCurrency(order.totalCents)}`, 552, y, { align: "right" }); if (order.notes) { y += 30; doc.setFontSize(9); doc.setTextColor(90, 101, 115); doc.text(`Note : ${order.notes}`, 44, y, { maxWidth: 500 }); } return new File([doc.output("blob")], `${order.orderNumber}.pdf`, { type: "application/pdf" }); }
function downloadOrderPdf(file: File) { const url = URL.createObjectURL(file); const link = document.createElement("a"); link.href = url; link.download = file.name; link.click(); URL.revokeObjectURL(url); }
function escapeHtml(value: string) { return value.replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[character] || character); }
function printOrder(supplier: any, orderNumber: string, items: Array<any>) { const total = items.reduce((sum, item) => sum + item.orderQuantity * item.purchasePriceCents, 0); const popup = window.open("", "_blank"); if (!popup) return toast.info("Bon créé. Autorisez les fenêtres contextuelles pour l’imprimer."); try { popup.opener = null; } catch { /* Navigation protégée selon le navigateur. */ } popup.document.write(`<!doctype html><html><head><title>${escapeHtml(orderNumber)}</title><style>body{font-family:Arial,sans-serif;color:#0f172a;padding:36px}header{display:flex;justify-content:space-between;border-bottom:2px solid #007B8B;padding-bottom:18px}h1{margin:0;color:#007B8B}table{width:100%;border-collapse:collapse;margin-top:26px}th,td{padding:11px;border-bottom:1px solid #dbe3eb;text-align:left}th:last-child,td:last-child{text-align:right}.total{text-align:right;margin-top:22px;font-size:19px;font-weight:700}small{color:#64748b}</style></head><body><header><div><h1>Bon de commande</h1><small>${escapeHtml(orderNumber)} · ${new Date().toLocaleDateString("fr-FR")}</small></div><div><strong>${escapeHtml(supplier.name)}</strong><br/><small>${escapeHtml(supplier.address || "")}</small></div></header><table><thead><tr><th>Produit</th><th>Référence</th><th>Quantité</th><th>Prix achat</th><th>Total</th></tr></thead><tbody>${items.map(item => `<tr><td>${escapeHtml(item.name)}</td><td>${escapeHtml(item.reference)}</td><td>${item.orderQuantity} ${escapeHtml(item.unit)}</td><td>${escapeHtml(formatCurrency(item.purchasePriceCents))}</td><td>${escapeHtml(formatCurrency(item.orderQuantity * item.purchasePriceCents))}</td></tr>`).join("")}</tbody></table><p class="total">Total : ${escapeHtml(formatCurrency(total))}</p></body></html>`); popup.document.close(); popup.focus(); setTimeout(() => popup.print(), 300); }
