import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useOffline, type SyncLogEntry } from "@/contexts/OfflineContext";
import { formatDate } from "@/lib/format";
import { CheckCircle2, CloudOff, CloudUpload, Clock3, RefreshCw, RotateCcw, Trash2, TriangleAlert } from "lucide-react";
import { useMemo, useState } from "react";

type Filter = "all" | SyncLogEntry["status"];
const statusMeta = { queued: { label: "En attente", tone: "bg-amber-400/10 text-amber-300", icon: Clock3 }, syncing: { label: "Synchronisation", tone: "bg-cyan-400/10 text-cyan-300", icon: RefreshCw }, succeeded: { label: "Réussie", tone: "bg-emerald-400/10 text-emerald-300", icon: CheckCircle2 }, failed: { label: "Échec", tone: "bg-rose-400/10 text-rose-300", icon: TriangleAlert } };

export default function SyncJournal() {
  const { isOnline, syncLog, pendingCount, failedCount, syncNow, retryOperation, clearCompletedSyncLog } = useOffline();
  const [filter, setFilter] = useState<Filter>("all");
  const entries = useMemo(() => filter === "all" ? syncLog : syncLog.filter(entry => entry.status === filter), [filter, syncLog]);
  return <div className="mx-auto max-w-6xl space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-medium uppercase tracking-[0.16em] text-primary">Mode hors connexion</p><h1 className="mt-2 text-2xl font-semibold tracking-tight text-white sm:text-3xl">Journal de synchronisation</h1></div><div className="flex flex-wrap gap-2"><Button onClick={() => void syncNow()} disabled={!isOnline || !pendingCount} className="bg-primary text-primary-foreground hover:bg-primary/90"><CloudUpload className="mr-2 h-4 w-4" />Synchroniser</Button><Button variant="outline" onClick={clearCompletedSyncLog} disabled={!syncLog.some(entry => entry.status === "succeeded")} className="border-white/10 text-slate-300"><Trash2 className="mr-2 h-4 w-4" />Effacer les réussies</Button></div></header><section className="grid gap-3 sm:grid-cols-3"><SummaryCard label="En attente" value={pendingCount} tone="cyan" icon={CloudUpload} /><SummaryCard label="Erreurs à reprendre" value={failedCount} tone="rose" icon={TriangleAlert} /><SummaryCard label="Connexion" value={isOnline ? "Disponible" : "Hors connexion"} tone={isOnline ? "emerald" : "amber"} icon={isOnline ? CheckCircle2 : CloudOff} /></section><div className="flex flex-wrap gap-2">{(["all", "queued", "syncing", "failed", "succeeded"] as Filter[]).map(value => <Button key={value} size="sm" variant={filter === value ? "default" : "outline"} onClick={() => setFilter(value)} className={filter === value ? "bg-primary text-primary-foreground hover:bg-primary/90" : "border-white/10 text-slate-300"}>{value === "all" ? "Toutes" : statusMeta[value].label}</Button>)}</div><section className="space-y-3">{entries.length ? entries.map(entry => <SyncCard key={entry.id} entry={entry} online={isOnline} onRetry={() => void retryOperation(entry.operationId)} />) : <div className="rounded-2xl border border-dashed border-white/10 px-6 py-16 text-center text-sm text-slate-500">Aucune synchronisation à afficher.</div>}</section></div>;
}
function SummaryCard({ label, value, tone, icon: Icon }: { label: string; value: string | number; tone: "cyan" | "rose" | "emerald" | "amber"; icon: typeof CloudUpload }) { const classes = { cyan: "bg-cyan-400/10 text-cyan-300", rose: "bg-rose-400/10 text-rose-300", emerald: "bg-emerald-400/10 text-emerald-300", amber: "bg-amber-400/10 text-amber-300" }; return <div className="rounded-2xl border border-white/[0.07] bg-[#111722] p-4"><div className="flex items-center justify-between"><p className="text-xs text-slate-400">{label}</p><span className={`grid h-9 w-9 place-items-center rounded-xl ${classes[tone]}`}><Icon className="h-4 w-4" /></span></div><p className="mt-3 text-xl font-semibold text-white">{value}</p></div>; }
function SyncCard({ entry, online, onRetry }: { entry: SyncLogEntry; online: boolean; onRetry: () => void }) { const meta = statusMeta[entry.status]; const Icon = meta.icon; return <article className="rounded-2xl border border-white/[0.07] bg-[#111722] p-4 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-medium text-slate-100">{entry.summary}</p><Badge className={`border-0 ${meta.tone}`}><Icon className={`mr-1 h-3.5 w-3.5 ${entry.status === "syncing" ? "animate-spin" : ""}`} />{meta.label}</Badge></div><p className="mt-2 text-xs text-slate-500">Créée le {formatDate(new Date(entry.createdAt))} · Dernière activité le {formatDate(new Date(entry.updatedAt))} · Tentative{entry.attemptCount > 1 ? "s" : ""} : {entry.attemptCount}</p>{entry.error && <div className="mt-3 rounded-xl border border-rose-400/15 bg-rose-400/[0.06] px-3 py-2 text-sm text-rose-200"><span className="font-medium">Cause : </span>{entry.error}</div>}</div>{entry.status === "failed" && <Button size="sm" onClick={onRetry} disabled={!online} className="shrink-0 bg-primary text-primary-foreground hover:bg-primary/90"><RotateCcw className="mr-2 h-3.5 w-3.5" />Reprendre</Button>}</div></article>; }
