import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { Boxes, Pencil, Plus, Ruler, Trash2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Restricted } from "./AuditLog";

type Unit = { id: number; name: string };
export default function Units() {
  const { user } = useAuth(); const isAdmin = user?.role === "admin"; const utils = trpc.useUtils(); const { data: units = [], isLoading } = trpc.units.list.useQuery(undefined, { enabled: isAdmin }); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Unit | null>(null); const [name, setName] = useState("");
  const refresh = () => { utils.units.list.invalidate(); utils.products.list.invalidate(); }; const close = () => { setOpen(false); setEditing(null); setName(""); };
  const create = trpc.units.create.useMutation({ onSuccess: () => { refresh(); close(); toast.success("Unité créée."); }, onError: error => toast.error(error.message) }); const update = trpc.units.update.useMutation({ onSuccess: () => { refresh(); close(); toast.success("Unité renommée et produits mis à jour."); }, onError: error => toast.error(error.message) }); const remove = trpc.units.remove.useMutation({ onSuccess: () => { refresh(); toast.success("Unité supprimée."); }, onError: error => toast.error(error.message) });
  const save = () => { const clean = name.trim(); if (!/^[A-Za-zÀ-ÖØ-öø-ÿ0-9\s'-]+$/.test(clean)) return toast.error("Caractères non autorisés"); if (!clean) return toast.error("Saisissez une unité de mesure."); if (editing) update.mutate({ id: editing.id, name: clean }); else create.mutate({ name: clean }); };
  if (!isAdmin) return <Restricted title="Unités de mesure" description="La gestion des unités est réservée aux administrateurs." />;
  return <div className="mx-auto max-w-5xl space-y-6"><header className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Catalogue</p><h1 className="mt-2 text-2xl font-semibold text-white sm:text-3xl">Unités de mesure</h1></div><Button onClick={() => { setEditing(null); setName(""); setOpen(true); }} className="bg-primary text-primary-foreground hover:bg-primary/90"><Plus className="mr-2 h-4 w-4" />Nouvelle unité</Button></header><Card className="border-white/[0.07] bg-[#111722]"><CardContent className="p-0">{isLoading ? <div className="px-6 py-16 text-center text-sm text-slate-500">Chargement des unités…</div> : units.length ? <div className="divide-y divide-white/[0.06]">{units.map(unit => <div key={unit.id} className="flex items-center justify-between gap-4 px-5 py-4"><div className="flex min-w-0 items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Ruler className="h-4 w-4" /></span><p className="truncate font-medium text-slate-100">{unit.name}</p></div><div className="flex gap-1"><Button size="icon" variant="ghost" onClick={() => { setEditing(unit); setName(unit.name); setOpen(true); }} className="text-primary"><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" onClick={() => { if (window.confirm(`Supprimer l’unité ${unit.name} ? Elle doit ne plus être utilisée par aucun produit.`)) remove.mutate({ id: unit.id }); }} className="text-rose-300"><Trash2 className="h-4 w-4" /></Button></div></div>)}</div> : <div className="px-6 py-16 text-center"><Boxes className="mx-auto h-7 w-7 text-slate-600" /><p className="mt-3 font-medium text-slate-300">Aucune unité</p><p className="mt-1 text-sm text-slate-500">Créez une unité avant d’ajouter un produit.</p></div>}</CardContent></Card><Dialog open={open} onOpenChange={value => !value && close()}><DialogContent className="border-white/10 bg-[#141b27] text-slate-100"><DialogHeader><DialogTitle>{editing ? "Modifier l’unité" : "Nouvelle unité"}</DialogTitle></DialogHeader><div className="space-y-2"><Label className="text-xs text-slate-300">Unité de mesure</Label><Input autoFocus value={name} onChange={event => setName(event.target.value)} onKeyDown={event => event.key === "Enter" && save()} placeholder="Ex. pièce, carton, kg" /></div><DialogFooter><Button variant="ghost" onClick={close}>Annuler</Button><Button onClick={save} disabled={create.isPending || update.isPending} className="bg-primary text-primary-foreground hover:bg-primary/90">{editing ? "Enregistrer" : "Créer"}</Button></DialogFooter></DialogContent></Dialog></div>;
}
